/* Generated by scripts/build-browser-adult-ruleset-v297.mjs — metadata of rules/adult-*.json.
 * Data: OISD NSFW (https://oisd.nl), GPL-3.0, see rules/LICENSE-OISD.txt and THIRD-PARTY-NOTICES.md.
 */
(function exposeAdultList(root) {
  const api = Object.freeze({
    "source": "OISD NSFW",
    "url": "https://nsfw.oisd.nl/domainswild2",
    "homepage": "https://oisd.nl",
    "license": "GPL-3.0",
    "version": "202609261407",
    "upstreamEntries": 506526,
    "sha256": "28175ee37f9e547e855352ab1eedeeb4362f727da7e3fa7db37eb13bdd4afeb7",
    "domains": 505602,
    "rules": 506,
    "rulesets": {
      "redirect": "adult_redirect",
      "block": "adult_block"
    }
  });
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.SatoruAdultList = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
