/* Generated by scripts/build-browser-adult-ruleset-v299.mjs — metadata of rules/adult-*.json.
 * Data: OISD NSFW and HaGeZi NSFW (GPL-3.0, rules/LICENSE-GPL-3.0.txt), StevenBlack porn-only (MIT,
 * rules/LICENSE-MIT-StevenBlack.txt), Satoru supplement (rules/adult-extra.txt). See THIRD-PARTY-NOTICES.md.
 */
(function exposeAdultList(root) {
  const api = Object.freeze({
    "source": "OISD NSFW + HaGeZi NSFW + StevenBlack + Satoru",
    "license": "GPL-3.0 (OISD, HaGeZi) · MIT (StevenBlack)",
    "version": "20260926",
    "domains": 535578,
    "rules": 536,
    "sources": [
      {
        "name": "OISD NSFW",
        "url": "https://nsfw.oisd.nl/domainswild2",
        "license": "GPL-3.0",
        "version": "202609261407",
        "sha256": "28175ee37f9e547e855352ab1eedeeb4362f727da7e3fa7db37eb13bdd4afeb7",
        "entries": 506526
      },
      {
        "name": "HaGeZi NSFW",
        "url": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nsfw-onlydomains.txt",
        "license": "GPL-3.0",
        "version": "2026.0926.1028.41",
        "sha256": "02b6b6007b7fa5b22be47f0f3ebff4827814c7f1a4eb4989b649bdb84e0dffd1",
        "entries": 85219
      },
      {
        "name": "StevenBlack porn-only",
        "url": "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts",
        "license": "MIT",
        "version": "25 September 2026 19:30:24 (UTC)",
        "sha256": "37c317fb4f7c39706c76088a3388c39adf94eeb6f7b61c6def1fe5016c55fa67",
        "entries": 76793
      },
      {
        "name": "Satoru supplement",
        "url": "rules/adult-extra.txt",
        "license": "Satoru",
        "version": "2026-09-26",
        "sha256": "acc8374b570bea0ba970157d28d055133e2658bf8247a1ed171900da04a4829f",
        "entries": 6
      }
    ],
    "rulesets": {
      "redirect": "adult_redirect",
      "block": "adult_block"
    }
  });
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.SatoruAdultList = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
