(function exposeSatoruAttentionI18n(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.SatoruAttentionI18n = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function buildI18n() {
  'use strict';

  const en = {
    appName: 'Satoru Attention', companionName: 'Browser companion', pinTitle: 'Keep Satoru visible', pinLead: 'Open the Extensions menu in the toolbar and pin Satoru Attention. The badge then shows whether a boundary is ready or active.', privacyLocal: 'Rules and session details stay in this browser. Satoru receives only installed/version and a minimal read-only status.',
    optionsTitle: 'Attention boundaries', optionsLead: 'Choose one site, one purpose and one limit. You can add more later.', configuredTitle: 'Configured sites', noSites: 'No sites are controlled yet.', setupTitle: 'Add one boundary', setupLead: 'The browser will ask permission only for the exact hostname you enter.',
    site: 'Site', customSite: 'Custom site', domain: 'Domain', purpose: 'Purpose', mode: 'Mode', minutes: 'Minutes', outcome: 'What should remain when you leave?', saveRule: 'Save boundary', enabled: 'On', paused: 'Paused', turnOn: 'Turn on', pause: 'Pause', settings: 'Settings',
    permissionMissing: 'Browser permission is missing for this domain.', permissionDenied: 'Permission was not granted. Nothing was changed.', saveSuccess: 'Boundary saved.', saveFailed: 'Could not save the boundary.', controlLocked: 'This Control session is active. Its rule cannot be changed until the session ends.', browserLimit: 'You can always disable or uninstall a browser extension. Control creates a real in-browser boundary, not an impossible-to-bypass OS lock.',
    outcomePlaceholder: 'For example: video published or one clear next step', domainPlaceholder: 'example.com',
    gateTitle: 'Name the reason before entering', gateLead: 'A short, explicit window replaces an open-ended feed.', noPolicyTitle: 'No boundary is configured', noPolicyLead: 'Open settings and add one site first.', runtimeErrorTitle: 'The browser boundary is temporarily unavailable', runtimeErrorLead: 'Your rules were not shown as empty. Retry when the extension is ready.', choosePurpose: 'Why are you opening it?', topic: 'Topic', topicPlaceholder: 'A specific topic for the references', duration: 'Time window', outcome: 'Result at the exit', startWindow: 'Open the bounded window',
    activeTitle: 'Your window is active', remaining: '{time} remaining', continueSite: 'Continue to the site', boundaryTitle: 'The chosen window ended', boundaryLead: 'Nothing was lost. Choose what is true now.', outcomeGroup: 'Session result', finishDone: 'Finished', finishRested: 'Rested as planned', finishEscaped: 'It pulled me in', finishUnknown: 'Close without assessment', extendOnce: 'Extend once',
    emergencyTitle: 'Emergency access', emergencyLead: 'Control has no ordinary extension. If access is genuinely needed, wait through the delay and name a short reason.', emergencyStart: 'Start emergency delay', emergencyWait: 'Available in {time}', emergencyReady: 'Emergency access can now be opened.', emergencyReason: 'Short reason', emergencyReasonPlaceholder: 'For example: urgent message', emergencyOpen: 'Open for 5 minutes', emergencySpent: 'The emergency pass for this period has already been used.',
    openSatoruGate: 'Open Satoru attention gate', openSatoruReturn: 'Open Satoru return', tryAgain: 'Try again', genericError: 'Something did not save. Try again.',
    popupTitle: 'Attention status', noActive: 'No active window.', configuredCount: '{count} configured sites', activeUntil: '{app}: {time} left', boundaryNow: '{app}: boundary reached', openGate: 'Open gate',
    purpose_publish: 'Publish', purpose_create: 'Create or edit', purpose_reply: 'Reply to people', purpose_research: 'Find specific references', purpose_watch: 'Watch one saved item', purpose_rest: 'Rest intentionally', purpose_unsure: 'Not sure yet',
    mode_trust: 'Trust', mode_adaptive: 'Adaptive', mode_control: 'Control',
    error_policy_unavailable: 'This site is not configured.', error_purpose_unavailable: 'This purpose is not enabled.', error_duration_invalid: 'Choose a duration inside the configured limit.', error_outcome_required: 'Name the result you expect to leave with.', error_topic_required: 'Name a specific research topic.', error_session_open: 'Another attention window is already active.', error_unsure_in_control: 'Control does not open without a stated purpose.', error_extension_unavailable: 'The one extension is unavailable.', error_emergency_delay: 'The emergency delay is still running.', error_reason_required: 'Add a short reason.', error_emergency_budget_spent: 'The emergency pass for this period has already been used.', error_clock_rollback: 'The device clock moved backwards. The site stays closed until time is corrected.', error_control_locked: 'The active Control rule cannot be changed.', error_permission_required: 'Grant permission for this exact hostname first.', error_runtime_unavailable: 'The extension is temporarily unavailable. Retry; your rules were not cleared.', error_storage_unavailable: 'Local storage is temporarily unavailable. Nothing was committed.', error_enforcement_failed: 'The browser could not apply the boundary. The change was rolled back; retry.', error_enforcement_recovery: 'The browser is restoring the previous boundary. Retry after a moment.',
  };

  const ru = {
    appName: 'Satoru Attention', companionName: 'Расширение для браузера', pinTitle: 'Оставь Satoru на виду', pinLead: 'Открой меню расширений на панели браузера и закрепи Satoru Attention. Значок покажет, готова ли граница и действует ли она сейчас.', privacyLocal: 'Правила и детали сессий остаются в этом браузере. Satoru получает только версию расширения и минимальный статус для чтения.',
    optionsTitle: 'Границы внимания', optionsLead: 'Выберите один сайт, одну цель и один лимит. Остальное можно добавить позже.', configuredTitle: 'Настроенные сайты', noSites: 'Пока ни один сайт не контролируется.', setupTitle: 'Добавить одну границу', setupLead: 'Браузер запросит доступ только к точно указанному имени хоста.',
    site: 'Сайт', customSite: 'Другой сайт', domain: 'Домен', purpose: 'Цель входа', mode: 'Режим', minutes: 'Минуты', outcome: 'Что должно остаться после выхода?', saveRule: 'Сохранить границу', enabled: 'Включено', paused: 'На паузе', turnOn: 'Включить', pause: 'Поставить на паузу', settings: 'Настройки',
    permissionMissing: 'Для этого домена нет разрешения браузера.', permissionDenied: 'Разрешение не выдано. Ничего не изменено.', saveSuccess: 'Граница сохранена.', saveFailed: 'Не удалось сохранить границу.', controlLocked: 'Сессия Control активна. Её правило нельзя менять до завершения.', browserLimit: 'Расширение всегда можно отключить или удалить в браузере. Control создаёт настоящую границу внутри браузера, но не неотключаемый системный замок.',
    outcomePlaceholder: 'Например: ролик опубликован или записан один следующий шаг', domainPlaceholder: 'example.com',
    gateTitle: 'Назовите причину до входа', gateLead: 'Короткое явное окно заменяет бесконечную ленту.', noPolicyTitle: 'Граница не настроена', noPolicyLead: 'Откройте настройки и сначала добавьте один сайт.', runtimeErrorTitle: 'Граница браузера временно недоступна', runtimeErrorLead: 'Правила не показаны как пустые. Повторите, когда расширение будет готово.', choosePurpose: 'Зачем вы его открываете?', topic: 'Тема', topicPlaceholder: 'Конкретная тема для референсов', duration: 'Окно времени', outcome: 'Результат на выходе', startWindow: 'Открыть ограниченное окно',
    activeTitle: 'Ваше окно активно', remaining: 'Осталось {time}', continueSite: 'Продолжить на сайте', boundaryTitle: 'Выбранное время закончилось', boundaryLead: 'Ничего не потеряно. Выберите то, что сейчас соответствует действительности.', outcomeGroup: 'Итог сессии', finishDone: 'Завершено', finishRested: 'Отдохнул как планировал', finishEscaped: 'Меня унесло', finishUnknown: 'Закрыть без оценки', extendOnce: 'Продлить один раз',
    emergencyTitle: 'Аварийный доступ', emergencyLead: 'В Control нет обычного продления. Если доступ действительно нужен, дождитесь задержки и кратко назовите причину.', emergencyStart: 'Запустить аварийную задержку', emergencyWait: 'Доступно через {time}', emergencyReady: 'Аварийный доступ теперь можно открыть.', emergencyReason: 'Короткая причина', emergencyReasonPlaceholder: 'Например: срочное сообщение', emergencyOpen: 'Открыть на 5 минут', emergencySpent: 'Аварийный пропуск на этот период уже использован.',
    openSatoruGate: 'Открыть гейт внимания Satoru', openSatoruReturn: 'Открыть возврат Satoru', tryAgain: 'Повторить', genericError: 'Не удалось сохранить. Попробуйте ещё раз.',
    popupTitle: 'Статус внимания', noActive: 'Активного окна нет.', configuredCount: 'Настроено сайтов: {count}', activeUntil: '{app}: осталось {time}', boundaryNow: '{app}: достигнута граница', openGate: 'Открыть гейт',
    purpose_publish: 'Опубликовать', purpose_create: 'Создать или смонтировать', purpose_reply: 'Ответить людям', purpose_research: 'Найти конкретные референсы', purpose_watch: 'Посмотреть один сохранённый материал', purpose_rest: 'Осознанно отдохнуть', purpose_unsure: 'Пока не знаю',
    mode_trust: 'Доверие', mode_adaptive: 'Адаптивный', mode_control: 'Контроль',
    error_policy_unavailable: 'Этот сайт не настроен.', error_purpose_unavailable: 'Эта цель входа не разрешена.', error_duration_invalid: 'Выберите время в пределах настроенного лимита.', error_outcome_required: 'Назовите результат, с которым хотите выйти.', error_topic_required: 'Назовите конкретную тему поиска.', error_session_open: 'Уже активно другое окно внимания.', error_unsure_in_control: 'Control не открывается без названной цели.', error_extension_unavailable: 'Единственное продление недоступно.', error_emergency_delay: 'Аварийная задержка ещё не закончилась.', error_reason_required: 'Добавьте короткую причину.', error_emergency_budget_spent: 'Аварийный пропуск на этот период уже использован.', error_clock_rollback: 'Часы устройства переведены назад. Сайт останется закрыт до исправления времени.', error_control_locked: 'Активное правило Control нельзя изменить.', error_permission_required: 'Сначала разрешите доступ к этому имени хоста.', error_runtime_unavailable: 'Расширение временно недоступно. Повторите: правила не были очищены.', error_storage_unavailable: 'Локальное хранилище временно недоступно. Изменение не зафиксировано.', error_enforcement_failed: 'Браузер не применил границу. Изменение отменено — повторите.', error_enforcement_recovery: 'Браузер восстанавливает предыдущую границу. Повторите через мгновение.',
  };

  const de = {
    appName: 'Satoru Attention', companionName: 'Browser-Begleiter', pinTitle: 'Satoru sichtbar halten', pinLead: 'Öffne das Erweiterungsmenü in der Symbolleiste und pinne Satoru Attention. Das Badge zeigt dann, ob eine Grenze bereit oder aktiv ist.', privacyLocal: 'Regeln und Sitzungsdetails bleiben in diesem Browser. Satoru erhält nur Version und einen minimalen Nur-Lese-Status.',
    optionsTitle: 'Aufmerksamkeitsgrenzen', optionsLead: 'Wähle eine Website, einen Zweck und ein Limit. Mehr kannst du später hinzufügen.', configuredTitle: 'Eingerichtete Websites', noSites: 'Noch wird keine Website kontrolliert.', setupTitle: 'Eine Grenze hinzufügen', setupLead: 'Der Browser fragt nur nach Zugriff auf den exakt eingegebenen Hostnamen.',
    site: 'Website', customSite: 'Andere Website', domain: 'Domain', purpose: 'Zweck', mode: 'Modus', minutes: 'Minuten', outcome: 'Was soll beim Verlassen übrig sein?', saveRule: 'Grenze speichern', enabled: 'Aktiv', paused: 'Pausiert', turnOn: 'Aktivieren', pause: 'Pausieren', settings: 'Einstellungen',
    permissionMissing: 'Die Browser-Berechtigung für diese Domain fehlt.', permissionDenied: 'Keine Berechtigung erteilt. Nichts wurde geändert.', saveSuccess: 'Grenze gespeichert.', saveFailed: 'Die Grenze konnte nicht gespeichert werden.', controlLocked: 'Diese Control-Sitzung ist aktiv. Die Regel kann bis zum Ende nicht geändert werden.', browserLimit: 'Eine Browser-Erweiterung kann immer deaktiviert oder entfernt werden. Control setzt eine echte Browser-Grenze, aber keine unabschaltbare Betriebssystemsperre.',
    outcomePlaceholder: 'Zum Beispiel: Video veröffentlicht oder ein klarer nächster Schritt', domainPlaceholder: 'example.com',
    gateTitle: 'Nenne vor dem Öffnen den Grund', gateLead: 'Ein kurzes, klares Zeitfenster ersetzt einen endlosen Feed.', noPolicyTitle: 'Keine Grenze eingerichtet', noPolicyLead: 'Öffne die Einstellungen und füge zuerst eine Website hinzu.', runtimeErrorTitle: 'Die Browsergrenze ist vorübergehend nicht verfügbar', runtimeErrorLead: 'Deine Regeln wurden nicht als leer angezeigt. Versuche es erneut, wenn die Erweiterung bereit ist.', choosePurpose: 'Warum öffnest du sie?', topic: 'Thema', topicPlaceholder: 'Ein konkretes Thema für Referenzen', duration: 'Zeitfenster', outcome: 'Ergebnis beim Verlassen', startWindow: 'Begrenztes Fenster öffnen',
    activeTitle: 'Dein Fenster ist aktiv', remaining: '{time} verbleibend', continueSite: 'Zur Website', boundaryTitle: 'Das gewählte Zeitfenster ist vorbei', boundaryLead: 'Nichts ist verloren. Wähle, was jetzt stimmt.', outcomeGroup: 'Sitzungsergebnis', finishDone: 'Erledigt', finishRested: 'Wie geplant erholt', finishEscaped: 'Ich bin im Feed gelandet', finishUnknown: 'Ohne Bewertung schließen', extendOnce: 'Einmal verlängern',
    emergencyTitle: 'Notfallzugang', emergencyLead: 'Control hat keine normale Verlängerung. Wenn der Zugriff wirklich nötig ist, warte die Verzögerung ab und nenne kurz den Grund.', emergencyStart: 'Notfallverzögerung starten', emergencyWait: 'Verfügbar in {time}', emergencyReady: 'Der Notfallzugang kann jetzt geöffnet werden.', emergencyReason: 'Kurzer Grund', emergencyReasonPlaceholder: 'Zum Beispiel: dringende Nachricht', emergencyOpen: 'Für 5 Minuten öffnen', emergencySpent: 'Der Notfallpass für diesen Zeitraum wurde bereits verwendet.',
    openSatoruGate: 'Satoru-Aufmerksamkeitsgate öffnen', openSatoruReturn: 'Satoru-Rückkehr öffnen', tryAgain: 'Erneut versuchen', genericError: 'Speichern fehlgeschlagen. Versuche es erneut.',
    popupTitle: 'Aufmerksamkeitsstatus', noActive: 'Kein aktives Fenster.', configuredCount: '{count} Websites eingerichtet', activeUntil: '{app}: noch {time}', boundaryNow: '{app}: Grenze erreicht', openGate: 'Gate öffnen',
    purpose_publish: 'Veröffentlichen', purpose_create: 'Erstellen oder bearbeiten', purpose_reply: 'Menschen antworten', purpose_research: 'Bestimmte Referenzen finden', purpose_watch: 'Ein gespeichertes Element ansehen', purpose_rest: 'Bewusst erholen', purpose_unsure: 'Noch unsicher',
    mode_trust: 'Vertrauen', mode_adaptive: 'Adaptiv', mode_control: 'Control',
    error_policy_unavailable: 'Diese Website ist nicht eingerichtet.', error_purpose_unavailable: 'Dieser Zweck ist nicht aktiviert.', error_duration_invalid: 'Wähle eine Dauer innerhalb des Limits.', error_outcome_required: 'Nenne das erwartete Ergebnis.', error_topic_required: 'Nenne ein konkretes Suchthema.', error_session_open: 'Ein anderes Aufmerksamkeitsfenster ist bereits aktiv.', error_unsure_in_control: 'Control öffnet nicht ohne klaren Zweck.', error_extension_unavailable: 'Die einmalige Verlängerung ist nicht verfügbar.', error_emergency_delay: 'Die Notfallverzögerung läuft noch.', error_reason_required: 'Gib einen kurzen Grund an.', error_emergency_budget_spent: 'Der Notfallpass wurde bereits verwendet.', error_clock_rollback: 'Die Geräteuhr wurde zurückgestellt. Die Website bleibt bis zur Korrektur geschlossen.', error_control_locked: 'Die aktive Control-Regel kann nicht geändert werden.', error_permission_required: 'Erlaube zuerst den Zugriff auf diesen exakten Hostnamen.', error_runtime_unavailable: 'Die Erweiterung ist vorübergehend nicht verfügbar. Deine Regeln wurden nicht gelöscht.', error_storage_unavailable: 'Der lokale Speicher ist vorübergehend nicht verfügbar. Nichts wurde übernommen.', error_enforcement_failed: 'Der Browser konnte die Grenze nicht anwenden. Die Änderung wurde zurückgesetzt.', error_enforcement_recovery: 'Der Browser stellt die vorherige Grenze wieder her. Versuche es gleich erneut.',
  };

  const uk = {
    appName: 'Satoru Attention', companionName: 'Розширення для браузера', pinTitle: 'Залиш Satoru на видноті', pinLead: 'Відкрий меню розширень на панелі браузера й закріпи Satoru Attention. Значок покаже, чи готова межа та чи діє вона зараз.', privacyLocal: 'Правила й деталі сесій залишаються в цьому браузері. Satoru отримує лише версію та мінімальний статус для читання.',
    optionsTitle: 'Межі уваги', optionsLead: 'Оберіть один сайт, одну мету й один ліміт. Решту можна додати пізніше.', configuredTitle: 'Налаштовані сайти', noSites: 'Поки жоден сайт не контролюється.', setupTitle: 'Додати одну межу', setupLead: 'Браузер попросить доступ лише до точно вказаного імені хоста.',
    site: 'Сайт', customSite: 'Інший сайт', domain: 'Домен', purpose: 'Мета входу', mode: 'Режим', minutes: 'Хвилини', outcome: 'Що має залишитися після виходу?', saveRule: 'Зберегти межу', enabled: 'Увімкнено', paused: 'На паузі', turnOn: 'Увімкнути', pause: 'Поставити на паузу', settings: 'Налаштування',
    permissionMissing: 'Немає дозволу браузера для цього домену.', permissionDenied: 'Дозвіл не надано. Нічого не змінено.', saveSuccess: 'Межу збережено.', saveFailed: 'Не вдалося зберегти межу.', controlLocked: 'Сесія Control активна. Її правило не можна змінювати до завершення.', browserLimit: 'Розширення завжди можна вимкнути або видалити в браузері. Control створює справжню межу в браузері, але не невідключний системний замок.',
    outcomePlaceholder: 'Наприклад: відео опубліковано або записано наступний крок', domainPlaceholder: 'example.com',
    gateTitle: 'Назвіть причину до входу', gateLead: 'Коротке явне вікно замінює нескінченну стрічку.', noPolicyTitle: 'Межу не налаштовано', noPolicyLead: 'Відкрийте налаштування й спочатку додайте один сайт.', runtimeErrorTitle: 'Межа браузера тимчасово недоступна', runtimeErrorLead: 'Правила не показано як порожні. Повторіть, коли розширення буде готове.', choosePurpose: 'Навіщо ви його відкриваєте?', topic: 'Тема', topicPlaceholder: 'Конкретна тема для референсів', duration: 'Часове вікно', outcome: 'Результат на виході', startWindow: 'Відкрити обмежене вікно',
    activeTitle: 'Ваше вікно активне', remaining: 'Залишилося {time}', continueSite: 'Продовжити на сайті', boundaryTitle: 'Обраний час завершився', boundaryLead: 'Нічого не втрачено. Оберіть те, що зараз відповідає дійсності.', outcomeGroup: 'Результат сесії', finishDone: 'Завершено', finishRested: 'Відпочив як планував', finishEscaped: 'Мене затягнуло', finishUnknown: 'Закрити без оцінки', extendOnce: 'Продовжити один раз',
    emergencyTitle: 'Аварійний доступ', emergencyLead: 'У Control немає звичайного продовження. Якщо доступ справді потрібен, дочекайтеся затримки й коротко назвіть причину.', emergencyStart: 'Запустити аварійну затримку', emergencyWait: 'Доступно через {time}', emergencyReady: 'Аварійний доступ тепер можна відкрити.', emergencyReason: 'Коротка причина', emergencyReasonPlaceholder: 'Наприклад: термінове повідомлення', emergencyOpen: 'Відкрити на 5 хвилин', emergencySpent: 'Аварійний пропуск на цей період уже використано.',
    openSatoruGate: 'Відкрити гейт уваги Satoru', openSatoruReturn: 'Відкрити повернення Satoru', tryAgain: 'Повторити', genericError: 'Не вдалося зберегти. Спробуйте ще раз.',
    popupTitle: 'Статус уваги', noActive: 'Активного вікна немає.', configuredCount: 'Налаштовано сайтів: {count}', activeUntil: '{app}: залишилося {time}', boundaryNow: '{app}: межу досягнуто', openGate: 'Відкрити гейт',
    purpose_publish: 'Опублікувати', purpose_create: 'Створити або змонтувати', purpose_reply: 'Відповісти людям', purpose_research: 'Знайти конкретні референси', purpose_watch: 'Переглянути один збережений матеріал', purpose_rest: 'Свідомо відпочити', purpose_unsure: 'Поки не знаю',
    mode_trust: 'Довіра', mode_adaptive: 'Адаптивний', mode_control: 'Контроль',
    error_policy_unavailable: 'Цей сайт не налаштовано.', error_purpose_unavailable: 'Цю мету входу не дозволено.', error_duration_invalid: 'Оберіть час у межах налаштованого ліміту.', error_outcome_required: 'Назвіть результат, з яким хочете вийти.', error_topic_required: 'Назвіть конкретну тему пошуку.', error_session_open: 'Інше вікно уваги вже активне.', error_unsure_in_control: 'Control не відкривається без названої мети.', error_extension_unavailable: 'Єдине продовження недоступне.', error_emergency_delay: 'Аварійна затримка ще триває.', error_reason_required: 'Додайте коротку причину.', error_emergency_budget_spent: 'Аварійний пропуск уже використано.', error_clock_rollback: 'Годинник пристрою переведено назад. Сайт залишиться закритим до виправлення часу.', error_control_locked: 'Активне правило Control не можна змінити.', error_permission_required: 'Спочатку надайте доступ до цього точного імені хоста.', error_runtime_unavailable: 'Розширення тимчасово недоступне. Правила не було очищено.', error_storage_unavailable: 'Локальне сховище тимчасово недоступне. Зміну не зафіксовано.', error_enforcement_failed: 'Браузер не застосував межу. Зміну скасовано — повторіть.', error_enforcement_recovery: 'Браузер відновлює попередню межу. Повторіть за мить.',
  };

  const es = {
    appName: 'Satoru Attention', companionName: 'Extensión del navegador', pinTitle: 'Mantén Satoru visible', pinLead: 'Abre el menú de extensiones de la barra y fija Satoru Attention. La insignia mostrará si hay un límite preparado o activo.', privacyLocal: 'Las reglas y los detalles de sesión permanecen en este navegador. Satoru solo recibe la versión y un estado mínimo de solo lectura.',
    optionsTitle: 'Límites de atención', optionsLead: 'Elige un sitio, un propósito y un límite. Puedes añadir más después.', configuredTitle: 'Sitios configurados', noSites: 'Todavía no se controla ningún sitio.', setupTitle: 'Añadir un límite', setupLead: 'El navegador pedirá acceso solo al nombre de host exacto que escribas.',
    site: 'Sitio', customSite: 'Otro sitio', domain: 'Dominio', purpose: 'Propósito', mode: 'Modo', minutes: 'Minutos', outcome: '¿Qué debe quedar al salir?', saveRule: 'Guardar límite', enabled: 'Activo', paused: 'En pausa', turnOn: 'Activar', pause: 'Pausar', settings: 'Ajustes',
    permissionMissing: 'Falta el permiso del navegador para este dominio.', permissionDenied: 'No se concedió permiso. No se cambió nada.', saveSuccess: 'Límite guardado.', saveFailed: 'No se pudo guardar el límite.', controlLocked: 'Esta sesión Control está activa. La regla no puede cambiarse hasta que termine.', browserLimit: 'Una extensión siempre puede desactivarse o eliminarse. Control crea un límite real dentro del navegador, no un bloqueo del sistema imposible de omitir.',
    outcomePlaceholder: 'Por ejemplo: vídeo publicado o un siguiente paso claro', domainPlaceholder: 'example.com',
    gateTitle: 'Nombra el motivo antes de entrar', gateLead: 'Una ventana breve y explícita sustituye un feed sin final.', noPolicyTitle: 'No hay un límite configurado', noPolicyLead: 'Abre los ajustes y añade primero un sitio.', runtimeErrorTitle: 'El límite del navegador no está disponible temporalmente', runtimeErrorLead: 'Tus reglas no se mostraron como vacías. Reintenta cuando la extensión esté lista.', choosePurpose: '¿Para qué lo abres?', topic: 'Tema', topicPlaceholder: 'Un tema concreto para las referencias', duration: 'Ventana de tiempo', outcome: 'Resultado al salir', startWindow: 'Abrir la ventana limitada',
    activeTitle: 'Tu ventana está activa', remaining: 'Quedan {time}', continueSite: 'Continuar al sitio', boundaryTitle: 'Terminó el tiempo elegido', boundaryLead: 'No se perdió nada. Elige lo que sea cierto ahora.', outcomeGroup: 'Resultado de la sesión', finishDone: 'Terminado', finishRested: 'Descansé como planeé', finishEscaped: 'Me arrastró el feed', finishUnknown: 'Cerrar sin evaluar', extendOnce: 'Ampliar una vez',
    emergencyTitle: 'Acceso de emergencia', emergencyLead: 'Control no tiene una ampliación normal. Si el acceso es realmente necesario, espera la demora e indica brevemente el motivo.', emergencyStart: 'Iniciar demora de emergencia', emergencyWait: 'Disponible en {time}', emergencyReady: 'Ya se puede abrir el acceso de emergencia.', emergencyReason: 'Motivo breve', emergencyReasonPlaceholder: 'Por ejemplo: mensaje urgente', emergencyOpen: 'Abrir durante 5 minutos', emergencySpent: 'El pase de emergencia de este periodo ya se usó.',
    openSatoruGate: 'Abrir el acceso de atención de Satoru', openSatoruReturn: 'Abrir el retorno de Satoru', tryAgain: 'Reintentar', genericError: 'No se pudo guardar. Inténtalo de nuevo.',
    popupTitle: 'Estado de atención', noActive: 'No hay una ventana activa.', configuredCount: '{count} sitios configurados', activeUntil: '{app}: quedan {time}', boundaryNow: '{app}: límite alcanzado', openGate: 'Abrir acceso',
    purpose_publish: 'Publicar', purpose_create: 'Crear o editar', purpose_reply: 'Responder a personas', purpose_research: 'Buscar referencias concretas', purpose_watch: 'Ver un elemento guardado', purpose_rest: 'Descansar conscientemente', purpose_unsure: 'Aún no lo sé',
    mode_trust: 'Confianza', mode_adaptive: 'Adaptativo', mode_control: 'Control',
    error_policy_unavailable: 'Este sitio no está configurado.', error_purpose_unavailable: 'Este propósito no está habilitado.', error_duration_invalid: 'Elige una duración dentro del límite.', error_outcome_required: 'Nombra el resultado que esperas obtener.', error_topic_required: 'Nombra un tema de búsqueda concreto.', error_session_open: 'Ya hay otra ventana de atención activa.', error_unsure_in_control: 'Control no abre sin un propósito definido.', error_extension_unavailable: 'La única ampliación no está disponible.', error_emergency_delay: 'La demora de emergencia sigue activa.', error_reason_required: 'Añade un motivo breve.', error_emergency_budget_spent: 'El pase de emergencia ya se usó.', error_clock_rollback: 'El reloj del dispositivo retrocedió. El sitio seguirá cerrado hasta corregir la hora.', error_control_locked: 'La regla Control activa no puede cambiarse.', error_permission_required: 'Primero concede acceso a este nombre de host exacto.', error_runtime_unavailable: 'La extensión no está disponible temporalmente. Tus reglas no se borraron.', error_storage_unavailable: 'El almacenamiento local no está disponible. No se guardó el cambio.', error_enforcement_failed: 'El navegador no pudo aplicar el límite. El cambio se revirtió.', error_enforcement_recovery: 'El navegador está restaurando el límite anterior. Reintenta en un momento.',
  };

  const TABLES = Object.freeze({ en: Object.freeze(en), ru: Object.freeze(ru), de: Object.freeze(de), uk: Object.freeze(uk), es: Object.freeze(es) });

  function locale(value) {
    const code = String(value || '').toLowerCase().split(/[-_]/)[0];
    return Object.prototype.hasOwnProperty.call(TABLES, code) ? code : 'en';
  }

  function translate(language, key, values = {}) {
    const table = TABLES[locale(language)];
    const source = table[key] || en[key] || key;
    return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), source);
  }

  function detect() {
    if (typeof chrome !== 'undefined' && chrome.i18n && chrome.i18n.getUILanguage) return locale(chrome.i18n.getUILanguage());
    if (typeof navigator !== 'undefined') return locale(navigator.language);
    return 'en';
  }

  function localizeDocument(language) {
    if (typeof document === 'undefined') return;
    const selected = locale(language || detect());
    document.documentElement.lang = selected;
    document.querySelectorAll('[data-i18n]').forEach((element) => {
      element.textContent = translate(selected, element.dataset.i18n);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
      element.setAttribute('placeholder', translate(selected, element.dataset.i18nPlaceholder));
    });
    document.querySelectorAll('[data-i18n-aria-label]').forEach((element) => {
      element.setAttribute('aria-label', translate(selected, element.dataset.i18nAriaLabel));
    });
  }

  return Object.freeze({ TABLES, locale, translate, detect, localizeDocument });
});
