(function exposeSatoruAttentionI18n(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.SatoruAttentionI18n = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function buildI18n() {
  'use strict';

  const en = {
    protectionName: 'Browser protection', protectionEyebrow: 'Local filter', protectionTitle: 'Browser protection', protectionOff: 'Off', protectionOn: 'On', protectionPaused: 'Recreation time', protectionLead: 'Block services, categories and custom domains before a page loads. Allowlist always wins.',
    enableProtection: 'Enable protection', enableProtectionLead: 'The browser asks for all-site access once so blocking and strict filters can work.', protectionCategories: 'Categories', categoriesLead: 'The catalog is bundled locally; browsing data is not sent anywhere.', categorySocial: 'Social networks', categoryVideo: 'Video streaming', categoryGaming: 'Online gaming', categoryDating: 'Dating', categoryGambling: 'Gambling', categoryAdult: 'Adult content', categoryPiracy: 'Piracy', domainCount: '{count} domains',
    denylistTitle: 'Denylist', denylistLead: 'A domain entry also blocks its subdomains.', allowlistTitle: 'Allowlist', allowlistLead: 'Allowed domains override categories and the denylist.', addDomain: 'Add', removeDomain: 'Remove {domain}', recreationTitle: 'Recreation time', recreationEnable: 'Pause categories and denylist on a schedule', recreationBypassNote: 'Bypass protection remains active.', recreationStart: 'Starts', recreationEnd: 'Ends', dayMon: 'Mon', dayTue: 'Tue', dayWed: 'Wed', dayThu: 'Thu', dayFri: 'Fri', daySat: 'Sat', daySun: 'Sun',
    strictFilters: 'Strict filters', safeSearch: 'Force SafeSearch', safeSearchLead: 'Google, Bing and DuckDuckGo searches receive strict parameters.', youtubeRestricted: 'YouTube Restricted Mode', youtubeRestrictedLead: 'Adds the official strict restriction header to YouTube requests.', blockBypass: 'Block bypass methods', blockBypassLead: 'Blocks known browser VPN, proxy, Tor and encrypted-DNS endpoints.', protectionLimit: 'This protects this browser. It cannot block another browser, an OS-level VPN, extension removal or incognito unless the extension is allowed there.', saveProtection: 'Apply protection', protectionCount: '{count} domains are covered', invalidDomain: 'Enter a valid domain.', chooseRecreationDay: 'Choose at least one recreation day.', protectionPermissionDenied: 'All-site permission was not granted. Protection was not changed.', protectionSaved: 'Protection applied to {count} domains.', error_protection_permission_required: 'Grant all-site access to enable protection.', error_runtime_reloading: 'The extension was updated. Reconnecting…', reconnectNow: 'Reconnect now',
    blockedEyebrow: 'Protection is active', blockedTitle: 'This address is blocked.', blockedLead: 'It matched a category, denylist entry or bypass-protection rule. The original address was not saved.', openProtectionSettings: 'Protection settings', returnToSatoru: 'Return to Satoru', blockedNoOverride: 'There is no instant override on this page.', nextProtectionChange: 'The next scheduled change is {time}.', protectionStillApplied: 'Protection remains active.',
    appName: 'Satoru Attention', companionName: 'Browser companion', pinTitle: 'Keep Satoru visible', pinLead: 'Open the Extensions menu in the toolbar and pin Satoru Attention. The badge then shows whether a boundary is ready or active.', privacyLocal: 'Rules and session details stay in this browser. Satoru receives only installed/version and a minimal read-only status.',
    optionsTitle: 'Controlled sites', optionsLead: 'Choose the allowed reasons before the impulse. At entry, you only name the concrete task.', configuredTitle: 'Configured sites', noSites: 'No sites are controlled yet.', setupTitle: 'Set up one site', setupLead: 'The browser will ask permission only for the exact hostname you enter.',
    site: 'Site', customSite: 'Custom site', domain: 'Domain', purpose: 'Purpose', mode: 'Mode', minutes: 'Minutes', outcome: 'What should remain when you leave?', saveRule: 'Save boundary', enabled: 'On', paused: 'Paused', turnOn: 'Turn on', pause: 'Pause', settings: 'Settings',
    permissionMissing: 'Browser permission is missing for this domain.', permissionDenied: 'Permission was not granted. Nothing was changed.', saveSuccess: 'Boundary saved.', saveFailed: 'Could not save the boundary.', controlLocked: 'This Control session is active. Its rule cannot be changed until the session ends.', browserLimit: 'You can always disable or uninstall a browser extension. Control creates a real in-browser boundary, not an impossible-to-bypass OS lock.',
    outcomePlaceholder: 'For example: video published or one clear next step', domainPlaceholder: 'example.com',
    gateTitle: 'Name the reason before entering', gateLead: 'A short, explicit window replaces an open-ended feed.', noPolicyTitle: 'No boundary is configured', noPolicyLead: 'Open settings and add one site first.', runtimeErrorTitle: 'The browser boundary is temporarily unavailable', runtimeErrorLead: 'The page lost its background connection. Existing rules were not changed.', choosePurpose: 'Why are you opening it?', topic: 'Topic', topicPlaceholder: 'A specific topic for the references', duration: 'Time window', outcome: 'Result at the exit', startWindow: 'Open the bounded window',
    activeTitle: 'Your window is active', remaining: '{time} remaining', continueSite: 'Continue to the site', boundaryTitle: 'The chosen window ended', boundaryLead: 'Nothing was lost. Choose what is true now.', outcomeGroup: 'Session result', finishDone: 'Finished', finishRested: 'Rested as planned', finishEscaped: 'It pulled me in', finishUnknown: 'Close without assessment', extendOnce: 'Extend once',
    emergencyTitle: 'Emergency access', emergencyLead: 'Control has no ordinary extension. If access is genuinely needed, wait through the delay and name a short reason.', emergencyStart: 'Start emergency delay', emergencyWait: 'Available in {time}', emergencyReady: 'Emergency access can now be opened.', emergencyReason: 'Short reason', emergencyReasonPlaceholder: 'For example: urgent message', emergencyOpen: 'Open for 5 minutes', emergencySpent: 'The emergency pass for this period has already been used.',
    openSatoruGate: 'Open Satoru attention gate', openSatoruReturn: 'Open Satoru return', tryAgain: 'Try again', genericError: 'Something did not save. Try again.',
    popupTitle: 'Attention status', noActive: 'No active window.', configuredCount: '{count} configured sites', activeUntil: '{app}: {time} left', boundaryNow: '{app}: boundary reached', openGate: 'Open gate',
    purpose_publish: 'Publish', purpose_create: 'Create or edit', purpose_reply: 'Reply to people', purpose_research: 'Find specific references', purpose_watch: 'Watch one saved item', purpose_rest: 'Rest intentionally', purpose_unsure: 'Not sure yet',
    mode_trust: 'Trust', mode_adaptive: 'Adaptive', mode_control: 'Control',
    error_policy_unavailable: 'This site is not configured.', error_purpose_unavailable: 'This purpose is not enabled.', error_duration_invalid: 'Choose a duration inside the configured limit.', error_outcome_required: 'Name the result you expect to leave with.', error_topic_required: 'Name a specific research topic.', error_session_open: 'Another attention window is already active.', error_unsure_in_control: 'Control does not open without a stated purpose.', error_extension_unavailable: 'The one extension is unavailable.', error_emergency_delay: 'The emergency delay is still running.', error_reason_required: 'Add a short reason.', error_emergency_budget_spent: 'The emergency pass for this period has already been used.', error_clock_rollback: 'The device clock moved backwards. The site stays closed until time is corrected.', error_control_locked: 'The active Control rule cannot be changed.', error_permission_required: 'Grant permission for this exact hostname first.', error_runtime_unavailable: 'The extension is temporarily unavailable. Retry; your rules were not cleared.', error_storage_unavailable: 'Local storage is temporarily unavailable. Nothing was committed.', error_enforcement_failed: 'The browser could not apply the boundary. The change was rolled back; retry.', error_enforcement_recovery: 'The browser is restoring the previous boundary. Retry after a moment.',
    allowedScenarios: 'Allowed entry scenarios', scenarioLead: 'These choices appear at the gate. A disabled scenario cannot be invented during an impulse.', dailyProtection: 'Daily protection', dailyBudget: 'Minutes per day', dailyEntries: 'Entries per day', cooldown: 'Pause between entries', delayedLoosening: 'Tighter changes apply now. Looser Control rules begin tomorrow.', runtimeHelpTitle: 'Reconnect the extension', runtimeHelpLead: 'Close this tab, reload Satoru Attention on the browser extensions page, then open Settings again. Existing rules were not changed.', policySummary: '{count} scenarios · {minutes} min/day · {sessions} entries', pendingTomorrow: 'A looser rule is scheduled for tomorrow.', cancelPending: 'Cancel change', editScenarios: 'Scenarios', pendingCancelled: 'Scheduled change cancelled.', changeTomorrow: 'The looser rule will begin tomorrow.',
    outcomePublish: 'Published item or an honest stop reason', outcomeCreate: 'Export, draft or one clear next step', outcomeReply: 'The named replies are sent', outcomeResearch: 'Up to three references and what you take from them', outcomeWatch: 'One chosen item and one takeaway', outcomeRest: 'A finite rest window', outcomeUnsure: 'No promised result',
    entryDetail: 'Concrete task', detailPlaceholder: 'For example: publish the Attention demo', expectedResult: 'Result at the exit', quotaSummary: '{used}/{max} entries · {minutes} minutes remain today', cooldownSummary: 'The next entry is available in {time}', dailyClosed: 'Today’s site budget is finished.', boundaryContext: '{purpose} · planned {minutes} min', finishUnfinished: 'Not finished, but stayed on task', finishEarly: 'Finished early',
    error_scenario_required: 'Enable at least one entry scenario.', error_daily_limits_invalid: 'Check the daily minutes, entry count and pause.', error_detail_required: 'Name the concrete task for this entry.', error_daily_sessions_spent: 'The allowed entries for today are used.', error_daily_budget_spent: 'The site’s daily time budget is used.', error_cooldown_active: 'The pause between entries is still active.',
  };

  const ru = {
    protectionName: 'Защита браузера', protectionEyebrow: 'Локальный фильтр', protectionTitle: 'Защита браузера', protectionOff: 'Выключена', protectionOn: 'Включена', protectionPaused: 'Время отдыха', protectionLead: 'Блокируй сервисы, категории и свои домены ещё до загрузки страницы. Белый список всегда важнее.',
    enableProtection: 'Включить защиту', enableProtectionLead: 'Браузер один раз запросит доступ ко всем сайтам для блокировки и строгих фильтров.', protectionCategories: 'Категории', categoriesLead: 'Каталог хранится внутри расширения; данные о просмотре никуда не отправляются.', categorySocial: 'Социальные сети', categoryVideo: 'Видеосервисы', categoryGaming: 'Онлайн-игры', categoryDating: 'Знакомства', categoryGambling: 'Азартные игры', categoryAdult: 'Контент 18+', categoryPiracy: 'Пиратские сайты', domainCount: '{count} доменов',
    denylistTitle: 'Чёрный список', denylistLead: 'Запись домена блокирует и все его поддомены.', allowlistTitle: 'Белый список', allowlistLead: 'Разрешённые домены важнее категорий и чёрного списка.', addDomain: 'Добавить', removeDomain: 'Удалить {domain}', recreationTitle: 'Время отдыха', recreationEnable: 'Отключать категории и чёрный список по расписанию', recreationBypassNote: 'Защита от обходов остаётся включённой.', recreationStart: 'Начало', recreationEnd: 'Конец', dayMon: 'Пн', dayTue: 'Вт', dayWed: 'Ср', dayThu: 'Чт', dayFri: 'Пт', daySat: 'Сб', daySun: 'Вс',
    strictFilters: 'Строгие фильтры', safeSearch: 'Принудительный SafeSearch', safeSearchLead: 'Поиск Google, Bing и DuckDuckGo получает строгие параметры.', youtubeRestricted: 'Ограниченный режим YouTube', youtubeRestrictedLead: 'Добавляет официальный строгий заголовок к запросам YouTube.', blockBypass: 'Блокировать способы обхода', blockBypassLead: 'Блокирует известные браузерные VPN, прокси, Tor и точки шифрованного DNS.', protectionLimit: 'Это защита данного браузера. Она не блокирует другой браузер, системный VPN, удаление расширения или инкогнито, если расширение там не разрешено.', saveProtection: 'Применить защиту', protectionCount: 'Под защитой {count} доменов', invalidDomain: 'Введите корректный домен.', chooseRecreationDay: 'Выберите хотя бы один день отдыха.', protectionPermissionDenied: 'Доступ ко всем сайтам не выдан. Защита не изменена.', protectionSaved: 'Защита применена к {count} доменам.', error_protection_permission_required: 'Разрешите доступ ко всем сайтам для включения защиты.', error_runtime_reloading: 'Расширение обновилось. Переподключаемся…', reconnectNow: 'Переподключить сейчас',
    blockedEyebrow: 'Защита включена', blockedTitle: 'Этот адрес заблокирован.', blockedLead: 'Он совпал с категорией, чёрным списком или правилом защиты от обхода. Исходный адрес не сохранён.', openProtectionSettings: 'Настройки защиты', returnToSatoru: 'Вернуться в Satoru', blockedNoOverride: 'На этой странице нет мгновенного обхода.', nextProtectionChange: 'Следующее изменение по расписанию: {time}.', protectionStillApplied: 'Защита продолжает действовать.',
    appName: 'Satoru Attention', companionName: 'Расширение для браузера', pinTitle: 'Оставь Satoru на виду', pinLead: 'Открой меню расширений на панели браузера и закрепи Satoru Attention. Значок покажет, готова ли граница и действует ли она сейчас.', privacyLocal: 'Правила и детали сессий остаются в этом браузере. Satoru получает только версию расширения и минимальный статус для чтения.',
    optionsTitle: 'Контролируемые сайты', optionsLead: 'Разрешённые причины выбираются заранее. На входе останется назвать только конкретную задачу.', configuredTitle: 'Настроенные сайты', noSites: 'Пока ни один сайт не контролируется.', setupTitle: 'Настроить один сайт', setupLead: 'Браузер запросит доступ только к точно указанному имени хоста.',
    site: 'Сайт', customSite: 'Другой сайт', domain: 'Домен', purpose: 'Цель входа', mode: 'Режим', minutes: 'Минуты', outcome: 'Что должно остаться после выхода?', saveRule: 'Сохранить границу', enabled: 'Включено', paused: 'На паузе', turnOn: 'Включить', pause: 'Поставить на паузу', settings: 'Настройки',
    permissionMissing: 'Для этого домена нет разрешения браузера.', permissionDenied: 'Разрешение не выдано. Ничего не изменено.', saveSuccess: 'Граница сохранена.', saveFailed: 'Не удалось сохранить границу.', controlLocked: 'Сессия Control активна. Её правило нельзя менять до завершения.', browserLimit: 'Расширение всегда можно отключить или удалить в браузере. Control создаёт настоящую границу внутри браузера, но не неотключаемый системный замок.',
    outcomePlaceholder: 'Например: ролик опубликован или записан один следующий шаг', domainPlaceholder: 'example.com',
    gateTitle: 'Назовите причину до входа', gateLead: 'Короткое явное окно заменяет бесконечную ленту.', noPolicyTitle: 'Граница не настроена', noPolicyLead: 'Откройте настройки и сначала добавьте один сайт.', runtimeErrorTitle: 'Граница браузера временно недоступна', runtimeErrorLead: 'Страница потеряла связь с фоновым модулем. Сохранённые правила не изменены.', choosePurpose: 'Зачем вы его открываете?', topic: 'Тема', topicPlaceholder: 'Конкретная тема для референсов', duration: 'Окно времени', outcome: 'Результат на выходе', startWindow: 'Открыть ограниченное окно',
    activeTitle: 'Ваше окно активно', remaining: 'Осталось {time}', continueSite: 'Продолжить на сайте', boundaryTitle: 'Выбранное время закончилось', boundaryLead: 'Ничего не потеряно. Выберите то, что сейчас соответствует действительности.', outcomeGroup: 'Итог сессии', finishDone: 'Завершено', finishRested: 'Отдохнул как планировал', finishEscaped: 'Меня унесло', finishUnknown: 'Закрыть без оценки', extendOnce: 'Продлить один раз',
    emergencyTitle: 'Аварийный доступ', emergencyLead: 'В Control нет обычного продления. Если доступ действительно нужен, дождитесь задержки и кратко назовите причину.', emergencyStart: 'Запустить аварийную задержку', emergencyWait: 'Доступно через {time}', emergencyReady: 'Аварийный доступ теперь можно открыть.', emergencyReason: 'Короткая причина', emergencyReasonPlaceholder: 'Например: срочное сообщение', emergencyOpen: 'Открыть на 5 минут', emergencySpent: 'Аварийный пропуск на этот период уже использован.',
    openSatoruGate: 'Открыть гейт внимания Satoru', openSatoruReturn: 'Открыть возврат Satoru', tryAgain: 'Повторить', genericError: 'Не удалось сохранить. Попробуйте ещё раз.',
    popupTitle: 'Статус внимания', noActive: 'Активного окна нет.', configuredCount: 'Настроено сайтов: {count}', activeUntil: '{app}: осталось {time}', boundaryNow: '{app}: достигнута граница', openGate: 'Открыть гейт',
    purpose_publish: 'Опубликовать', purpose_create: 'Создать или смонтировать', purpose_reply: 'Ответить людям', purpose_research: 'Найти конкретные референсы', purpose_watch: 'Посмотреть один сохранённый материал', purpose_rest: 'Осознанно отдохнуть', purpose_unsure: 'Пока не знаю',
    mode_trust: 'Доверие', mode_adaptive: 'Адаптивный', mode_control: 'Контроль',
    error_policy_unavailable: 'Этот сайт не настроен.', error_purpose_unavailable: 'Эта цель входа не разрешена.', error_duration_invalid: 'Выберите время в пределах настроенного лимита.', error_outcome_required: 'Назовите результат, с которым хотите выйти.', error_topic_required: 'Назовите конкретную тему поиска.', error_session_open: 'Уже активно другое окно внимания.', error_unsure_in_control: 'Control не открывается без названной цели.', error_extension_unavailable: 'Единственное продление недоступно.', error_emergency_delay: 'Аварийная задержка ещё не закончилась.', error_reason_required: 'Добавьте короткую причину.', error_emergency_budget_spent: 'Аварийный пропуск на этот период уже использован.', error_clock_rollback: 'Часы устройства переведены назад. Сайт останется закрыт до исправления времени.', error_control_locked: 'Активное правило Control нельзя изменить.', error_permission_required: 'Сначала разрешите доступ к этому имени хоста.', error_runtime_unavailable: 'Связь с фоновым модулем расширения потеряна. Сохранённые правила не изменены.', error_storage_unavailable: 'Локальное хранилище временно недоступно. Изменение не зафиксировано.', error_enforcement_failed: 'Браузер не применил границу. Изменение отменено — повторите.', error_enforcement_recovery: 'Браузер восстанавливает предыдущую границу. Повторите через мгновение.',
    allowedScenarios: 'Разрешённые сценарии входа', scenarioLead: 'Только эти варианты появятся на входе. Отключённый сценарий нельзя придумать в момент импульса.', dailyProtection: 'Защита на день', dailyBudget: 'Минут в день', dailyEntries: 'Входов в день', cooldown: 'Пауза между входами', delayedLoosening: 'Усиление действует сразу. Ослабление Control — со следующего дня.', runtimeHelpTitle: 'Переподключите расширение', runtimeHelpLead: 'Закройте эту вкладку, перезагрузите Satoru Attention на странице расширений браузера и снова откройте настройки. Сохранённые правила не изменены.', policySummary: '{count} сценария · {minutes} мин/день · {sessions} входа', pendingTomorrow: 'Ослабление правила запланировано на завтра.', cancelPending: 'Отменить изменение', editScenarios: 'Сценарии', pendingCancelled: 'Отложенное изменение отменено.', changeTomorrow: 'Ослабление начнёт действовать завтра.',
    outcomePublish: 'Публикация или честная причина остановки', outcomeCreate: 'Экспорт, черновик или один ясный следующий шаг', outcomeReply: 'Названные ответы отправлены', outcomeResearch: 'До трёх референсов и что из них берёте', outcomeWatch: 'Один выбранный материал и один вывод', outcomeRest: 'Конечное окно отдыха', outcomeUnsure: 'Нет обещанного результата',
    entryDetail: 'Конкретная задача', detailPlaceholder: 'Например: опубликовать демо Attention', expectedResult: 'Результат на выходе', quotaSummary: '{used}/{max} входа · сегодня осталось {minutes} мин', cooldownSummary: 'Следующий вход будет доступен через {time}', dailyClosed: 'Дневной бюджет сайта закончился.', boundaryContext: '{purpose} · план {minutes} мин', finishUnfinished: 'Не закончил, но оставался по делу', finishEarly: 'Завершить раньше',
    error_scenario_required: 'Включите хотя бы один сценарий входа.', error_daily_limits_invalid: 'Проверьте минуты, число входов и паузу.', error_detail_required: 'Назовите конкретную задачу этого входа.', error_daily_sessions_spent: 'Разрешённые входы на сегодня закончились.', error_daily_budget_spent: 'Дневной бюджет времени на этот сайт закончился.', error_cooldown_active: 'Пауза между входами ещё не закончилась.',
  };

  const de = {
    protectionName: 'Browser-Schutz', protectionEyebrow: 'Lokaler Filter', protectionTitle: 'Browser-Schutz', protectionOff: 'Aus', protectionOn: 'An', protectionPaused: 'Freizeit', protectionLead: 'Dienste, Kategorien und eigene Domains vor dem Laden blockieren. Die Erlaubnisliste gewinnt immer.',
    enableProtection: 'Schutz aktivieren', enableProtectionLead: 'Der Browser fragt einmal nach Zugriff auf alle Websites.', protectionCategories: 'Kategorien', categoriesLead: 'Der Katalog liegt lokal in der Erweiterung; Browserdaten werden nicht gesendet.', categorySocial: 'Soziale Netzwerke', categoryVideo: 'Videostreaming', categoryGaming: 'Online-Spiele', categoryDating: 'Dating', categoryGambling: 'Glücksspiel', categoryAdult: 'Inhalte ab 18', categoryPiracy: 'Piraterie', domainCount: '{count} Domains',
    denylistTitle: 'Sperrliste', denylistLead: 'Ein Domain-Eintrag sperrt auch alle Subdomains.', allowlistTitle: 'Erlaubnisliste', allowlistLead: 'Erlaubte Domains überschreiben Kategorien und Sperrliste.', addDomain: 'Hinzufügen', removeDomain: '{domain} entfernen', recreationTitle: 'Freizeit', recreationEnable: 'Kategorien und Sperrliste nach Zeitplan pausieren', recreationBypassNote: 'Der Umgehungsschutz bleibt aktiv.', recreationStart: 'Beginn', recreationEnd: 'Ende', dayMon: 'Mo', dayTue: 'Di', dayWed: 'Mi', dayThu: 'Do', dayFri: 'Fr', daySat: 'Sa', daySun: 'So',
    strictFilters: 'Strenge Filter', safeSearch: 'SafeSearch erzwingen', safeSearchLead: 'Google-, Bing- und DuckDuckGo-Suchen erhalten strenge Parameter.', youtubeRestricted: 'Eingeschränkter YouTube-Modus', youtubeRestrictedLead: 'Fügt YouTube-Anfragen den offiziellen strengen Header hinzu.', blockBypass: 'Umgehungsmethoden blockieren', blockBypassLead: 'Blockiert bekannte Browser-VPNs, Proxys, Tor und verschlüsselte DNS-Endpunkte.', protectionLimit: 'Dies schützt diesen Browser, nicht andere Browser, System-VPNs oder eine entfernte Erweiterung. Inkognito wird nur geschützt, wenn die Erweiterung dort erlaubt ist.', saveProtection: 'Schutz anwenden', protectionCount: '{count} Domains geschützt', invalidDomain: 'Gib eine gültige Domain ein.', chooseRecreationDay: 'Wähle mindestens einen Freizeittag.', protectionPermissionDenied: 'Der Zugriff auf alle Websites wurde nicht erteilt.', protectionSaved: 'Schutz auf {count} Domains angewendet.', error_protection_permission_required: 'Erlaube den Zugriff auf alle Websites.', error_runtime_reloading: 'Die Erweiterung wurde aktualisiert. Verbindung wird hergestellt…', reconnectNow: 'Jetzt verbinden',
    blockedEyebrow: 'Schutz ist aktiv', blockedTitle: 'Diese Adresse ist gesperrt.', blockedLead: 'Sie entspricht einer Kategorie, der Sperrliste oder einer Umgehungsschutz-Regel. Die ursprüngliche Adresse wurde nicht gespeichert.', openProtectionSettings: 'Schutzeinstellungen', returnToSatoru: 'Zurück zu Satoru', blockedNoOverride: 'Auf dieser Seite gibt es keine sofortige Ausnahme.', nextProtectionChange: 'Nächste geplante Änderung: {time}.', protectionStillApplied: 'Der Schutz bleibt aktiv.',
    appName: 'Satoru Attention', companionName: 'Browser-Begleiter', pinTitle: 'Satoru sichtbar halten', pinLead: 'Öffne das Erweiterungsmenü in der Symbolleiste und pinne Satoru Attention. Das Badge zeigt dann, ob eine Grenze bereit oder aktiv ist.', privacyLocal: 'Regeln und Sitzungsdetails bleiben in diesem Browser. Satoru erhält nur Version und einen minimalen Nur-Lese-Status.',
    optionsTitle: 'Kontrollierte Websites', optionsLead: 'Lege erlaubte Gründe vor dem Impuls fest. Beim Einstieg nennst du nur die konkrete Aufgabe.', configuredTitle: 'Eingerichtete Websites', noSites: 'Noch wird keine Website kontrolliert.', setupTitle: 'Eine Website einrichten', setupLead: 'Der Browser fragt nur nach Zugriff auf den exakt eingegebenen Hostnamen.',
    site: 'Website', customSite: 'Andere Website', domain: 'Domain', purpose: 'Zweck', mode: 'Modus', minutes: 'Minuten', outcome: 'Was soll beim Verlassen übrig sein?', saveRule: 'Grenze speichern', enabled: 'Aktiv', paused: 'Pausiert', turnOn: 'Aktivieren', pause: 'Pausieren', settings: 'Einstellungen',
    permissionMissing: 'Die Browser-Berechtigung für diese Domain fehlt.', permissionDenied: 'Keine Berechtigung erteilt. Nichts wurde geändert.', saveSuccess: 'Grenze gespeichert.', saveFailed: 'Die Grenze konnte nicht gespeichert werden.', controlLocked: 'Diese Control-Sitzung ist aktiv. Die Regel kann bis zum Ende nicht geändert werden.', browserLimit: 'Eine Browser-Erweiterung kann immer deaktiviert oder entfernt werden. Control setzt eine echte Browser-Grenze, aber keine unabschaltbare Betriebssystemsperre.',
    outcomePlaceholder: 'Zum Beispiel: Video veröffentlicht oder ein klarer nächster Schritt', domainPlaceholder: 'example.com',
    gateTitle: 'Nenne vor dem Öffnen den Grund', gateLead: 'Ein kurzes, klares Zeitfenster ersetzt einen endlosen Feed.', noPolicyTitle: 'Keine Grenze eingerichtet', noPolicyLead: 'Öffne die Einstellungen und füge zuerst eine Website hinzu.', runtimeErrorTitle: 'Die Browsergrenze ist vorübergehend nicht verfügbar', runtimeErrorLead: 'Die Seite hat die Verbindung zum Hintergrundmodul verloren. Bestehende Regeln wurden nicht geändert.', choosePurpose: 'Warum öffnest du sie?', topic: 'Thema', topicPlaceholder: 'Ein konkretes Thema für Referenzen', duration: 'Zeitfenster', outcome: 'Ergebnis beim Verlassen', startWindow: 'Begrenztes Fenster öffnen',
    activeTitle: 'Dein Fenster ist aktiv', remaining: '{time} verbleibend', continueSite: 'Zur Website', boundaryTitle: 'Das gewählte Zeitfenster ist vorbei', boundaryLead: 'Nichts ist verloren. Wähle, was jetzt stimmt.', outcomeGroup: 'Sitzungsergebnis', finishDone: 'Erledigt', finishRested: 'Wie geplant erholt', finishEscaped: 'Ich bin im Feed gelandet', finishUnknown: 'Ohne Bewertung schließen', extendOnce: 'Einmal verlängern',
    emergencyTitle: 'Notfallzugang', emergencyLead: 'Control hat keine normale Verlängerung. Wenn der Zugriff wirklich nötig ist, warte die Verzögerung ab und nenne kurz den Grund.', emergencyStart: 'Notfallverzögerung starten', emergencyWait: 'Verfügbar in {time}', emergencyReady: 'Der Notfallzugang kann jetzt geöffnet werden.', emergencyReason: 'Kurzer Grund', emergencyReasonPlaceholder: 'Zum Beispiel: dringende Nachricht', emergencyOpen: 'Für 5 Minuten öffnen', emergencySpent: 'Der Notfallpass für diesen Zeitraum wurde bereits verwendet.',
    openSatoruGate: 'Satoru-Aufmerksamkeitsgate öffnen', openSatoruReturn: 'Satoru-Rückkehr öffnen', tryAgain: 'Erneut versuchen', genericError: 'Speichern fehlgeschlagen. Versuche es erneut.',
    popupTitle: 'Aufmerksamkeitsstatus', noActive: 'Kein aktives Fenster.', configuredCount: '{count} Websites eingerichtet', activeUntil: '{app}: noch {time}', boundaryNow: '{app}: Grenze erreicht', openGate: 'Gate öffnen',
    purpose_publish: 'Veröffentlichen', purpose_create: 'Erstellen oder bearbeiten', purpose_reply: 'Menschen antworten', purpose_research: 'Bestimmte Referenzen finden', purpose_watch: 'Ein gespeichertes Element ansehen', purpose_rest: 'Bewusst erholen', purpose_unsure: 'Noch unsicher',
    mode_trust: 'Vertrauen', mode_adaptive: 'Adaptiv', mode_control: 'Control',
    error_policy_unavailable: 'Diese Website ist nicht eingerichtet.', error_purpose_unavailable: 'Dieser Zweck ist nicht aktiviert.', error_duration_invalid: 'Wähle eine Dauer innerhalb des Limits.', error_outcome_required: 'Nenne das erwartete Ergebnis.', error_topic_required: 'Nenne ein konkretes Suchthema.', error_session_open: 'Ein anderes Aufmerksamkeitsfenster ist bereits aktiv.', error_unsure_in_control: 'Control öffnet nicht ohne klaren Zweck.', error_extension_unavailable: 'Die einmalige Verlängerung ist nicht verfügbar.', error_emergency_delay: 'Die Notfallverzögerung läuft noch.', error_reason_required: 'Gib einen kurzen Grund an.', error_emergency_budget_spent: 'Der Notfallpass wurde bereits verwendet.', error_clock_rollback: 'Die Geräteuhr wurde zurückgestellt. Die Website bleibt bis zur Korrektur geschlossen.', error_control_locked: 'Die aktive Control-Regel kann nicht geändert werden.', error_permission_required: 'Erlaube zuerst den Zugriff auf diesen exakten Hostnamen.', error_runtime_unavailable: 'Die Erweiterung ist vorübergehend nicht verfügbar. Deine Regeln wurden nicht gelöscht.', error_storage_unavailable: 'Der lokale Speicher ist vorübergehend nicht verfügbar. Nichts wurde übernommen.', error_enforcement_failed: 'Der Browser konnte die Grenze nicht anwenden. Die Änderung wurde zurückgesetzt.', error_enforcement_recovery: 'Der Browser stellt die vorherige Grenze wieder her. Versuche es gleich erneut.',
    allowedScenarios: 'Erlaubte Einstiegsszenarien', scenarioLead: 'Nur diese Optionen erscheinen am Gate. Ein deaktiviertes Szenario kann nicht spontan erfunden werden.', dailyProtection: 'Tagesschutz', dailyBudget: 'Minuten pro Tag', dailyEntries: 'Einstiege pro Tag', cooldown: 'Pause zwischen Einstiegen', delayedLoosening: 'Strengere Änderungen gelten sofort. Lockerere Control-Regeln erst morgen.', runtimeHelpTitle: 'Erweiterung neu verbinden', runtimeHelpLead: 'Schließe diesen Tab, lade Satoru Attention auf der Erweiterungsseite neu und öffne die Einstellungen erneut. Bestehende Regeln wurden nicht geändert.', policySummary: '{count} Szenarien · {minutes} Min/Tag · {sessions} Einstiege', pendingTomorrow: 'Eine lockerere Regel ist für morgen geplant.', cancelPending: 'Änderung abbrechen', editScenarios: 'Szenarien', pendingCancelled: 'Geplante Änderung abgebrochen.', changeTomorrow: 'Die lockerere Regel gilt ab morgen.',
    outcomePublish: 'Veröffentlicht oder ehrlicher Stoppgrund', outcomeCreate: 'Export, Entwurf oder ein klarer nächster Schritt', outcomeReply: 'Die genannten Antworten sind gesendet', outcomeResearch: 'Bis zu drei Referenzen und was du übernimmst', outcomeWatch: 'Ein gewählter Inhalt und eine Erkenntnis', outcomeRest: 'Ein endliches Erholungsfenster', outcomeUnsure: 'Kein versprochenes Ergebnis',
    entryDetail: 'Konkrete Aufgabe', detailPlaceholder: 'Zum Beispiel: Attention-Demo veröffentlichen', expectedResult: 'Ergebnis beim Verlassen', quotaSummary: '{used}/{max} Einstiege · heute noch {minutes} Minuten', cooldownSummary: 'Der nächste Einstieg ist in {time} möglich', dailyClosed: 'Das Tagesbudget der Website ist aufgebraucht.', boundaryContext: '{purpose} · geplant {minutes} Min', finishUnfinished: 'Nicht fertig, aber bei der Aufgabe geblieben', finishEarly: 'Früher beenden',
    error_scenario_required: 'Aktiviere mindestens ein Einstiegsszenario.', error_daily_limits_invalid: 'Prüfe Tagesminuten, Einstiege und Pause.', error_detail_required: 'Nenne die konkrete Aufgabe für diesen Einstieg.', error_daily_sessions_spent: 'Die erlaubten Einstiege für heute sind aufgebraucht.', error_daily_budget_spent: 'Das tägliche Zeitbudget dieser Website ist aufgebraucht.', error_cooldown_active: 'Die Pause zwischen Einstiegen läuft noch.',
  };

  const uk = {
    protectionName: 'Захист браузера', protectionEyebrow: 'Локальний фільтр', protectionTitle: 'Захист браузера', protectionOff: 'Вимкнено', protectionOn: 'Увімкнено', protectionPaused: 'Час відпочинку', protectionLead: 'Блокуй сервіси, категорії та власні домени до завантаження сторінки. Білий список завжди важливіший.',
    enableProtection: 'Увімкнути захист', enableProtectionLead: 'Браузер один раз попросить доступ до всіх сайтів.', protectionCategories: 'Категорії', categoriesLead: 'Каталог зберігається локально; дані перегляду нікуди не надсилаються.', categorySocial: 'Соціальні мережі', categoryVideo: 'Відеосервіси', categoryGaming: 'Онлайн-ігри', categoryDating: 'Знайомства', categoryGambling: 'Азартні ігри', categoryAdult: 'Контент 18+', categoryPiracy: 'Піратські сайти', domainCount: '{count} доменів',
    denylistTitle: 'Чорний список', denylistLead: 'Запис домену блокує також усі піддомени.', allowlistTitle: 'Білий список', allowlistLead: 'Дозволені домени важливіші за категорії та чорний список.', addDomain: 'Додати', removeDomain: 'Видалити {domain}', recreationTitle: 'Час відпочинку', recreationEnable: 'Призупиняти категорії та чорний список за розкладом', recreationBypassNote: 'Захист від обходу залишається активним.', recreationStart: 'Початок', recreationEnd: 'Кінець', dayMon: 'Пн', dayTue: 'Вт', dayWed: 'Ср', dayThu: 'Чт', dayFri: 'Пт', daySat: 'Сб', daySun: 'Нд',
    strictFilters: 'Суворі фільтри', safeSearch: 'Примусовий SafeSearch', safeSearchLead: 'Пошуки Google, Bing і DuckDuckGo отримують суворі параметри.', youtubeRestricted: 'Обмежений режим YouTube', youtubeRestrictedLead: 'Додає офіційний суворий заголовок до запитів YouTube.', blockBypass: 'Блокувати способи обходу', blockBypassLead: 'Блокує відомі браузерні VPN, проксі, Tor і точки шифрованого DNS.', protectionLimit: 'Це захист цього браузера. Він не блокує інший браузер, системний VPN, видалення розширення чи інкогніто без дозволу розширення.', saveProtection: 'Застосувати захист', protectionCount: 'Захищено {count} доменів', invalidDomain: 'Введіть коректний домен.', chooseRecreationDay: 'Оберіть хоча б один день відпочинку.', protectionPermissionDenied: 'Доступ до всіх сайтів не надано.', protectionSaved: 'Захист застосовано до {count} доменів.', error_protection_permission_required: 'Дозвольте доступ до всіх сайтів.', error_runtime_reloading: 'Розширення оновилося. Перепідключення…', reconnectNow: 'Перепідключити зараз',
    blockedEyebrow: 'Захист увімкнено', blockedTitle: 'Цю адресу заблоковано.', blockedLead: 'Вона збіглася з категорією, чорним списком або правилом захисту від обходу. Початкову адресу не збережено.', openProtectionSettings: 'Налаштування захисту', returnToSatoru: 'Повернутися в Satoru', blockedNoOverride: 'На цій сторінці немає миттєвого обходу.', nextProtectionChange: 'Наступна зміна за розкладом: {time}.', protectionStillApplied: 'Захист продовжує діяти.',
    appName: 'Satoru Attention', companionName: 'Розширення для браузера', pinTitle: 'Залиш Satoru на видноті', pinLead: 'Відкрий меню розширень на панелі браузера й закріпи Satoru Attention. Значок покаже, чи готова межа та чи діє вона зараз.', privacyLocal: 'Правила й деталі сесій залишаються в цьому браузері. Satoru отримує лише версію та мінімальний статус для читання.',
    optionsTitle: 'Контрольовані сайти', optionsLead: 'Дозволені причини обираються заздалегідь. На вході треба назвати лише конкретне завдання.', configuredTitle: 'Налаштовані сайти', noSites: 'Поки жоден сайт не контролюється.', setupTitle: 'Налаштувати один сайт', setupLead: 'Браузер попросить доступ лише до точно вказаного імені хоста.',
    site: 'Сайт', customSite: 'Інший сайт', domain: 'Домен', purpose: 'Мета входу', mode: 'Режим', minutes: 'Хвилини', outcome: 'Що має залишитися після виходу?', saveRule: 'Зберегти межу', enabled: 'Увімкнено', paused: 'На паузі', turnOn: 'Увімкнути', pause: 'Поставити на паузу', settings: 'Налаштування',
    permissionMissing: 'Немає дозволу браузера для цього домену.', permissionDenied: 'Дозвіл не надано. Нічого не змінено.', saveSuccess: 'Межу збережено.', saveFailed: 'Не вдалося зберегти межу.', controlLocked: 'Сесія Control активна. Її правило не можна змінювати до завершення.', browserLimit: 'Розширення завжди можна вимкнути або видалити в браузері. Control створює справжню межу в браузері, але не невідключний системний замок.',
    outcomePlaceholder: 'Наприклад: відео опубліковано або записано наступний крок', domainPlaceholder: 'example.com',
    gateTitle: 'Назвіть причину до входу', gateLead: 'Коротке явне вікно замінює нескінченну стрічку.', noPolicyTitle: 'Межу не налаштовано', noPolicyLead: 'Відкрийте налаштування й спочатку додайте один сайт.', runtimeErrorTitle: 'Межа браузера тимчасово недоступна', runtimeErrorLead: 'Сторінка втратила зв’язок із фоновим модулем. Збережені правила не змінено.', choosePurpose: 'Навіщо ви його відкриваєте?', topic: 'Тема', topicPlaceholder: 'Конкретна тема для референсів', duration: 'Часове вікно', outcome: 'Результат на виході', startWindow: 'Відкрити обмежене вікно',
    activeTitle: 'Ваше вікно активне', remaining: 'Залишилося {time}', continueSite: 'Продовжити на сайті', boundaryTitle: 'Обраний час завершився', boundaryLead: 'Нічого не втрачено. Оберіть те, що зараз відповідає дійсності.', outcomeGroup: 'Результат сесії', finishDone: 'Завершено', finishRested: 'Відпочив як планував', finishEscaped: 'Мене затягнуло', finishUnknown: 'Закрити без оцінки', extendOnce: 'Продовжити один раз',
    emergencyTitle: 'Аварійний доступ', emergencyLead: 'У Control немає звичайного продовження. Якщо доступ справді потрібен, дочекайтеся затримки й коротко назвіть причину.', emergencyStart: 'Запустити аварійну затримку', emergencyWait: 'Доступно через {time}', emergencyReady: 'Аварійний доступ тепер можна відкрити.', emergencyReason: 'Коротка причина', emergencyReasonPlaceholder: 'Наприклад: термінове повідомлення', emergencyOpen: 'Відкрити на 5 хвилин', emergencySpent: 'Аварійний пропуск на цей період уже використано.',
    openSatoruGate: 'Відкрити гейт уваги Satoru', openSatoruReturn: 'Відкрити повернення Satoru', tryAgain: 'Повторити', genericError: 'Не вдалося зберегти. Спробуйте ще раз.',
    popupTitle: 'Статус уваги', noActive: 'Активного вікна немає.', configuredCount: 'Налаштовано сайтів: {count}', activeUntil: '{app}: залишилося {time}', boundaryNow: '{app}: межу досягнуто', openGate: 'Відкрити гейт',
    purpose_publish: 'Опублікувати', purpose_create: 'Створити або змонтувати', purpose_reply: 'Відповісти людям', purpose_research: 'Знайти конкретні референси', purpose_watch: 'Переглянути один збережений матеріал', purpose_rest: 'Свідомо відпочити', purpose_unsure: 'Поки не знаю',
    mode_trust: 'Довіра', mode_adaptive: 'Адаптивний', mode_control: 'Контроль',
    error_policy_unavailable: 'Цей сайт не налаштовано.', error_purpose_unavailable: 'Цю мету входу не дозволено.', error_duration_invalid: 'Оберіть час у межах налаштованого ліміту.', error_outcome_required: 'Назвіть результат, з яким хочете вийти.', error_topic_required: 'Назвіть конкретну тему пошуку.', error_session_open: 'Інше вікно уваги вже активне.', error_unsure_in_control: 'Control не відкривається без названої мети.', error_extension_unavailable: 'Єдине продовження недоступне.', error_emergency_delay: 'Аварійна затримка ще триває.', error_reason_required: 'Додайте коротку причину.', error_emergency_budget_spent: 'Аварійний пропуск уже використано.', error_clock_rollback: 'Годинник пристрою переведено назад. Сайт залишиться закритим до виправлення часу.', error_control_locked: 'Активне правило Control не можна змінити.', error_permission_required: 'Спочатку надайте доступ до цього точного імені хоста.', error_runtime_unavailable: 'Зв’язок із фоновим модулем розширення втрачено. Збережені правила не змінено.', error_storage_unavailable: 'Локальне сховище тимчасово недоступне. Зміну не зафіксовано.', error_enforcement_failed: 'Браузер не застосував межу. Зміну скасовано — повторіть.', error_enforcement_recovery: 'Браузер відновлює попередню межу. Повторіть за мить.',
    allowedScenarios: 'Дозволені сценарії входу', scenarioLead: 'Лише ці варіанти з’являться на вході. Вимкнений сценарій не можна вигадати в момент імпульсу.', dailyProtection: 'Захист на день', dailyBudget: 'Хвилин на день', dailyEntries: 'Входів на день', cooldown: 'Пауза між входами', delayedLoosening: 'Посилення діє одразу. Послаблення Control — з наступного дня.', runtimeHelpTitle: 'Перепідключіть розширення', runtimeHelpLead: 'Закрийте цю вкладку, перезавантажте Satoru Attention на сторінці розширень браузера й знову відкрийте налаштування. Збережені правила не змінено.', policySummary: '{count} сценарії · {minutes} хв/день · {sessions} входи', pendingTomorrow: 'Послаблення правила заплановано на завтра.', cancelPending: 'Скасувати зміну', editScenarios: 'Сценарії', pendingCancelled: 'Відкладену зміну скасовано.', changeTomorrow: 'Послаблення почне діяти завтра.',
    outcomePublish: 'Публікація або чесна причина зупинки', outcomeCreate: 'Експорт, чернетка або один ясний наступний крок', outcomeReply: 'Названі відповіді надіслано', outcomeResearch: 'До трьох референсів і що з них берете', outcomeWatch: 'Один обраний матеріал і один висновок', outcomeRest: 'Скінченне вікно відпочинку', outcomeUnsure: 'Немає обіцяного результату',
    entryDetail: 'Конкретне завдання', detailPlaceholder: 'Наприклад: опублікувати демо Attention', expectedResult: 'Результат на виході', quotaSummary: '{used}/{max} входи · сьогодні залишилося {minutes} хв', cooldownSummary: 'Наступний вхід буде доступний через {time}', dailyClosed: 'Денний бюджет сайту закінчився.', boundaryContext: '{purpose} · план {minutes} хв', finishUnfinished: 'Не завершив, але залишався у справі', finishEarly: 'Завершити раніше',
    error_scenario_required: 'Увімкніть хоча б один сценарій входу.', error_daily_limits_invalid: 'Перевірте хвилини, кількість входів і паузу.', error_detail_required: 'Назвіть конкретне завдання цього входу.', error_daily_sessions_spent: 'Дозволені входи на сьогодні закінчилися.', error_daily_budget_spent: 'Денний бюджет часу на цей сайт закінчився.', error_cooldown_active: 'Пауза між входами ще не закінчилася.',
  };

  const es = {
    protectionName: 'Protección del navegador', protectionEyebrow: 'Filtro local', protectionTitle: 'Protección del navegador', protectionOff: 'Desactivada', protectionOn: 'Activa', protectionPaused: 'Tiempo libre', protectionLead: 'Bloquea servicios, categorías y dominios propios antes de cargar la página. La lista permitida siempre prevalece.',
    enableProtection: 'Activar protección', enableProtectionLead: 'El navegador pedirá una vez acceso a todos los sitios.', protectionCategories: 'Categorías', categoriesLead: 'El catálogo está incluido localmente; los datos de navegación no se envían.', categorySocial: 'Redes sociales', categoryVideo: 'Vídeo en streaming', categoryGaming: 'Juegos en línea', categoryDating: 'Citas', categoryGambling: 'Apuestas', categoryAdult: 'Contenido para adultos', categoryPiracy: 'Piratería', domainCount: '{count} dominios',
    denylistTitle: 'Lista bloqueada', denylistLead: 'Una entrada de dominio también bloquea sus subdominios.', allowlistTitle: 'Lista permitida', allowlistLead: 'Los dominios permitidos prevalecen sobre categorías y bloqueos.', addDomain: 'Añadir', removeDomain: 'Eliminar {domain}', recreationTitle: 'Tiempo libre', recreationEnable: 'Pausar categorías y bloqueos según un horario', recreationBypassNote: 'La protección contra evasiones sigue activa.', recreationStart: 'Inicio', recreationEnd: 'Fin', dayMon: 'Lun', dayTue: 'Mar', dayWed: 'Mié', dayThu: 'Jue', dayFri: 'Vie', daySat: 'Sáb', daySun: 'Dom',
    strictFilters: 'Filtros estrictos', safeSearch: 'Forzar SafeSearch', safeSearchLead: 'Las búsquedas de Google, Bing y DuckDuckGo reciben parámetros estrictos.', youtubeRestricted: 'Modo restringido de YouTube', youtubeRestrictedLead: 'Añade el encabezado estricto oficial a las solicitudes de YouTube.', blockBypass: 'Bloquear métodos de evasión', blockBypassLead: 'Bloquea VPN de navegador, proxys, Tor y endpoints DNS cifrados conocidos.', protectionLimit: 'Esto protege este navegador. No bloquea otro navegador, una VPN del sistema, la eliminación de la extensión ni incógnito sin permiso.', saveProtection: 'Aplicar protección', protectionCount: '{count} dominios protegidos', invalidDomain: 'Introduce un dominio válido.', chooseRecreationDay: 'Elige al menos un día de tiempo libre.', protectionPermissionDenied: 'No se concedió acceso a todos los sitios.', protectionSaved: 'Protección aplicada a {count} dominios.', error_protection_permission_required: 'Concede acceso a todos los sitios.', error_runtime_reloading: 'La extensión se actualizó. Reconectando…', reconnectNow: 'Reconectar ahora',
    blockedEyebrow: 'La protección está activa', blockedTitle: 'Esta dirección está bloqueada.', blockedLead: 'Coincide con una categoría, una entrada bloqueada o una regla contra evasiones. La dirección original no se guardó.', openProtectionSettings: 'Ajustes de protección', returnToSatoru: 'Volver a Satoru', blockedNoOverride: 'Esta página no ofrece una excepción instantánea.', nextProtectionChange: 'Próximo cambio programado: {time}.', protectionStillApplied: 'La protección sigue activa.',
    appName: 'Satoru Attention', companionName: 'Extensión del navegador', pinTitle: 'Mantén Satoru visible', pinLead: 'Abre el menú de extensiones de la barra y fija Satoru Attention. La insignia mostrará si hay un límite preparado o activo.', privacyLocal: 'Las reglas y los detalles de sesión permanecen en este navegador. Satoru solo recibe la versión y un estado mínimo de solo lectura.',
    optionsTitle: 'Sitios controlados', optionsLead: 'Elige los motivos permitidos antes del impulso. Al entrar solo nombras la tarea concreta.', configuredTitle: 'Sitios configurados', noSites: 'Todavía no se controla ningún sitio.', setupTitle: 'Configurar un sitio', setupLead: 'El navegador pedirá acceso solo al nombre de host exacto que escribas.',
    site: 'Sitio', customSite: 'Otro sitio', domain: 'Dominio', purpose: 'Propósito', mode: 'Modo', minutes: 'Minutos', outcome: '¿Qué debe quedar al salir?', saveRule: 'Guardar límite', enabled: 'Activo', paused: 'En pausa', turnOn: 'Activar', pause: 'Pausar', settings: 'Ajustes',
    permissionMissing: 'Falta el permiso del navegador para este dominio.', permissionDenied: 'No se concedió permiso. No se cambió nada.', saveSuccess: 'Límite guardado.', saveFailed: 'No se pudo guardar el límite.', controlLocked: 'Esta sesión Control está activa. La regla no puede cambiarse hasta que termine.', browserLimit: 'Una extensión siempre puede desactivarse o eliminarse. Control crea un límite real dentro del navegador, no un bloqueo del sistema imposible de omitir.',
    outcomePlaceholder: 'Por ejemplo: vídeo publicado o un siguiente paso claro', domainPlaceholder: 'example.com',
    gateTitle: 'Nombra el motivo antes de entrar', gateLead: 'Una ventana breve y explícita sustituye un feed sin final.', noPolicyTitle: 'No hay un límite configurado', noPolicyLead: 'Abre los ajustes y añade primero un sitio.', runtimeErrorTitle: 'El límite del navegador no está disponible temporalmente', runtimeErrorLead: 'La página perdió la conexión con el módulo en segundo plano. Las reglas existentes no cambiaron.', choosePurpose: '¿Para qué lo abres?', topic: 'Tema', topicPlaceholder: 'Un tema concreto para las referencias', duration: 'Ventana de tiempo', outcome: 'Resultado al salir', startWindow: 'Abrir la ventana limitada',
    activeTitle: 'Tu ventana está activa', remaining: 'Quedan {time}', continueSite: 'Continuar al sitio', boundaryTitle: 'Terminó el tiempo elegido', boundaryLead: 'No se perdió nada. Elige lo que sea cierto ahora.', outcomeGroup: 'Resultado de la sesión', finishDone: 'Terminado', finishRested: 'Descansé como planeé', finishEscaped: 'Me arrastró el feed', finishUnknown: 'Cerrar sin evaluar', extendOnce: 'Ampliar una vez',
    emergencyTitle: 'Acceso de emergencia', emergencyLead: 'Control no tiene una ampliación normal. Si el acceso es realmente necesario, espera la demora e indica brevemente el motivo.', emergencyStart: 'Iniciar demora de emergencia', emergencyWait: 'Disponible en {time}', emergencyReady: 'Ya se puede abrir el acceso de emergencia.', emergencyReason: 'Motivo breve', emergencyReasonPlaceholder: 'Por ejemplo: mensaje urgente', emergencyOpen: 'Abrir durante 5 minutos', emergencySpent: 'El pase de emergencia de este periodo ya se usó.',
    openSatoruGate: 'Abrir el acceso de atención de Satoru', openSatoruReturn: 'Abrir el retorno de Satoru', tryAgain: 'Reintentar', genericError: 'No se pudo guardar. Inténtalo de nuevo.',
    popupTitle: 'Estado de atención', noActive: 'No hay una ventana activa.', configuredCount: '{count} sitios configurados', activeUntil: '{app}: quedan {time}', boundaryNow: '{app}: límite alcanzado', openGate: 'Abrir acceso',
    purpose_publish: 'Publicar', purpose_create: 'Crear o editar', purpose_reply: 'Responder a personas', purpose_research: 'Buscar referencias concretas', purpose_watch: 'Ver un elemento guardado', purpose_rest: 'Descansar conscientemente', purpose_unsure: 'Aún no lo sé',
    mode_trust: 'Confianza', mode_adaptive: 'Adaptativo', mode_control: 'Control',
    error_policy_unavailable: 'Este sitio no está configurado.', error_purpose_unavailable: 'Este propósito no está habilitado.', error_duration_invalid: 'Elige una duración dentro del límite.', error_outcome_required: 'Nombra el resultado que esperas obtener.', error_topic_required: 'Nombra un tema de búsqueda concreto.', error_session_open: 'Ya hay otra ventana de atención activa.', error_unsure_in_control: 'Control no abre sin un propósito definido.', error_extension_unavailable: 'La única ampliación no está disponible.', error_emergency_delay: 'La demora de emergencia sigue activa.', error_reason_required: 'Añade un motivo breve.', error_emergency_budget_spent: 'El pase de emergencia ya se usó.', error_clock_rollback: 'El reloj del dispositivo retrocedió. El sitio seguirá cerrado hasta corregir la hora.', error_control_locked: 'La regla Control activa no puede cambiarse.', error_permission_required: 'Primero concede acceso a este nombre de host exacto.', error_runtime_unavailable: 'La extensión no está disponible temporalmente. Tus reglas no se borraron.', error_storage_unavailable: 'El almacenamiento local no está disponible. No se guardó el cambio.', error_enforcement_failed: 'El navegador no pudo aplicar el límite. El cambio se revirtió.', error_enforcement_recovery: 'El navegador está restaurando el límite anterior. Reintenta en un momento.',
    allowedScenarios: 'Escenarios de entrada permitidos', scenarioLead: 'Solo estas opciones aparecen en la puerta. Un escenario desactivado no puede inventarse durante el impulso.', dailyProtection: 'Protección diaria', dailyBudget: 'Minutos al día', dailyEntries: 'Entradas al día', cooldown: 'Pausa entre entradas', delayedLoosening: 'Los cambios más estrictos se aplican ahora. Las reglas Control más flexibles empiezan mañana.', runtimeHelpTitle: 'Vuelve a conectar la extensión', runtimeHelpLead: 'Cierra esta pestaña, recarga Satoru Attention en la página de extensiones y abre Ajustes de nuevo. Las reglas existentes no cambiaron.', policySummary: '{count} escenarios · {minutes} min/día · {sessions} entradas', pendingTomorrow: 'Hay una regla más flexible programada para mañana.', cancelPending: 'Cancelar cambio', editScenarios: 'Escenarios', pendingCancelled: 'Cambio programado cancelado.', changeTomorrow: 'La regla más flexible empezará mañana.',
    outcomePublish: 'Publicación o motivo honesto para parar', outcomeCreate: 'Exportación, borrador o un siguiente paso claro', outcomeReply: 'Las respuestas indicadas están enviadas', outcomeResearch: 'Hasta tres referencias y qué tomas de ellas', outcomeWatch: 'Un material elegido y una conclusión', outcomeRest: 'Una ventana de descanso finita', outcomeUnsure: 'Sin resultado prometido',
    entryDetail: 'Tarea concreta', detailPlaceholder: 'Por ejemplo: publicar la demo de Attention', expectedResult: 'Resultado al salir', quotaSummary: '{used}/{max} entradas · quedan {minutes} minutos hoy', cooldownSummary: 'La siguiente entrada estará disponible en {time}', dailyClosed: 'El presupuesto diario del sitio terminó.', boundaryContext: '{purpose} · plan {minutes} min', finishUnfinished: 'No terminé, pero seguí con la tarea', finishEarly: 'Terminar antes',
    error_scenario_required: 'Activa al menos un escenario de entrada.', error_daily_limits_invalid: 'Revisa los minutos, entradas y pausa diarios.', error_detail_required: 'Nombra la tarea concreta de esta entrada.', error_daily_sessions_spent: 'Ya usaste las entradas permitidas de hoy.', error_daily_budget_spent: 'Ya usaste el tiempo diario de este sitio.', error_cooldown_active: 'La pausa entre entradas sigue activa.',
  };

  const TABLES = Object.freeze({ en: Object.freeze(en), ru: Object.freeze(ru), de: Object.freeze(de), uk: Object.freeze(uk), es: Object.freeze(es) });

  function locale(value) {
    const code = String(value || '').toLowerCase().split(/[-_]/)[0];
    return Object.prototype.hasOwnProperty.call(TABLES, code) ? code : 'en';
  }

  function translate(language, key, values = {}) {
    const table = TABLES[locale(language)];
    const source = table[key] || en[key] || key;
    return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), source);
  }

  function detect() {
    if (typeof chrome !== 'undefined' && chrome.i18n && chrome.i18n.getUILanguage) return locale(chrome.i18n.getUILanguage());
    if (typeof navigator !== 'undefined') return locale(navigator.language);
    return 'en';
  }

  function localizeDocument(language) {
    if (typeof document === 'undefined') return;
    const selected = locale(language || detect());
    document.documentElement.lang = selected;
    document.querySelectorAll('[data-i18n]').forEach((element) => {
      element.textContent = translate(selected, element.dataset.i18n);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
      element.setAttribute('placeholder', translate(selected, element.dataset.i18nPlaceholder));
    });
    document.querySelectorAll('[data-i18n-aria-label]').forEach((element) => {
      element.setAttribute('aria-label', translate(selected, element.dataset.i18nAriaLabel));
    });
  }

  return Object.freeze({ TABLES, locale, translate, detect, localizeDocument });
});
