import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,mutate,validateTask,save,load,nextTask,dayTasks,conflicts,duration,STORAGE_KEY} from './site/model.js';
const storage=()=>{const map=new Map();return {setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k)??null};};
test('all fixtures survive validated persistence',()=>{for(const kind of ['regular','dense','empty']){const s=storage(),state=fixture(kind);save(s,state);assert.deepEqual(load(s),state);}});
test('completion does not lose tasks and has a reversible result',()=>{const state=fixture(),next=mutate(state,{type:'toggle',id:'video'});assert.equal(state.tasks[1].done,false);assert.equal(next.tasks[1].done,true);assert.deepEqual(mutate(next,{type:'toggle',id:'video'}),state);});
test('core priority, not array-first completed task, defines next action',()=>assert.equal(nextTask(fixture()).id,'video'));
test('one core per day without changing another day',()=>{const state=fixture();state.tasks.push({...state.tasks[1],id:'tomorrow',date:'2026-09-08'});const next=mutate(state,{type:'core',id:'study'});assert.deepEqual(next.tasks.filter(t=>t.core).map(t=>t.id),['study','tomorrow']);});
test('first empty day, then stable-id add is idempotent',()=>{const s=fixture('empty'),task={...fixture().tasks[1],id:'new'};const one=mutate(s,{type:'add',task});assert.equal(mutate(one,{type:'add',task}).tasks.length,1);});
test('time and duration validated; no wildcard categories',()=>{const task=fixture().tasks[1];for(const patch of [{time:'25:61'},{minutes:0},{minutes:-5},{minutes:'bad'},{title:' '},{title:'x'.repeat(161)},{sphere:'<script>'}])assert.throws(()=>validateTask({...task,...patch}));});
test('overlap and touching intervals differ',()=>{const tasks=fixture().tasks,t=tasks[1];assert.deepEqual(conflicts(t,tasks),[]);assert.deepEqual(conflicts({...t,minutes:60},tasks),['study']);assert.deepEqual(conflicts({...t,minutes:45},tasks),[]);});
test('failed write/readback is not success',()=>{assert.throws(()=>save({setItem(){throw Error('full');}},fixture()));assert.throws(()=>save({setItem(){},getItem(){return null;}},fixture()));});
test('corrupt storage is not treated as an empty profile',()=>{const s=storage();s.setItem(STORAGE_KEY,'broken');assert.throws(()=>load(s));});
test('day switching does not duplicate or relocate tasks',()=>{const s=fixture(),next=mutate(s,{type:'day',day:'2026-09-08'});assert.equal(dayTasks(next).length,0);assert.equal(next.tasks.length,s.tasks.length);});
test('closing a day preserves unfinished tasks, reversible',()=>{const s=fixture(),closed=mutate(s,{type:'close'});assert.deepEqual(closed.tasks,s.tasks);assert.deepEqual(mutate(closed,{type:'close'}),s);});
test('completed active focus is stopped, other focus not stopped',()=>{const s=fixture();s.timer={id:'video',running:true};assert.equal(mutate(s,{type:'toggle',id:'video'}).timer,null);assert.deepEqual(mutate(s,{type:'toggle',id:'study'}).timer,s.timer);});
test('notes and text recap have independent persistence',()=>{let s=mutate(fixture(),{type:'note',id:'n',text:'  Мысль  '});s=mutate(s,{type:'recap',text:'Итог'});const disk=storage();save(disk,s);assert.equal(load(disk).notes[0].text,'Мысль');assert.equal(load(disk).recaps[s.day],'Итог');});
test('duration has readable units',()=>{assert.equal(duration(25),'25 мин');assert.equal(duration(90),'1 ч 30 мин');});
test('habit completion belongs to selected day, not every date',()=>{let s=mutate(fixture(),{type:'habit',id:'read'});s=mutate(s,{type:'day',day:'2026-09-08'});assert.equal(s.habitDays['2026-09-07'].read,true);assert.equal(s.habitDays[s.day],undefined);s=mutate(s,{type:'habit',id:'read'});assert.equal(s.habitDays['2026-09-08'].read,true);assert.equal(s.habitDays['2026-09-07'].read,true);});
