import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../art-factory/avatar-3d-v1-20260907/package.json',import.meta.url));
const {chromium}=require('playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['microphone']});
const page=await context.newPage(),errors=[],failures=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(r.url());});page.on('dialog',d=>d.accept());
await mkdir(new URL('./qa/',import.meta.url),{recursive:true});
const shot=async(name)=>page.screenshot({path:new URL('./qa/'+name+'.png',import.meta.url).pathname,fullPage:true});
try{
  await page.goto('http://127.0.0.1:4179');await page.evaluate(()=>document.fonts.ready);
  await shot('today-1440');
  assert.deepEqual(await page.locator('img').evaluateAll(images=>images.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)),[]);
  assert.ok(await page.locator('#composer').evaluate(el=>el.getBoundingClientRect().bottom<innerHeight));
  assert.equal(await page.locator('.task').count(),5);
  await page.getByRole('button',{name:'Выполнить: Записать первый дубль для Satoru',exact:true}).click();
  assert.ok(await page.locator('[data-task="video"]').evaluate(el=>el.classList.contains('done')));
  await page.getByRole('button',{name:'Отменить',exact:true}).click();
  assert.equal(await page.locator('[data-task="video"].done').count(),0);
  await page.getByRole('button',{name:'Время начала: Записать первый дубль для Satoru',exact:true}).click();
  await page.locator('#edit-form input[name=time]').fill('16:45');await page.locator('#edit-form button.primary').click();
  assert.equal(await page.locator('[data-task="video"] .task-time').innerText(),'16:45');
  await page.getByLabel('Длительность: Записать первый дубль для Satoru',{exact:true}).click();
  await page.locator('#edit-form input[name=minutes]').fill('45');await page.locator('#edit-form button.primary').click();
  assert.ok(await page.locator('[data-task="video"] .notice-conflict').isVisible());
  await page.locator('#task-name').fill('Проверить & сохранить <тест>');await page.locator('#composer input[name=time]').fill('20:40');await page.locator('#composer button[type=submit]').click();
  assert.equal(await page.locator('.task').count(),6);await page.reload();assert.equal(await page.locator('.task').count(),6);
  await page.locator('[data-task="video"] [data-start]').click();await page.locator('[data-timer-toggle]').click();assert.equal(await page.locator('[data-timer-toggle]').innerText(),'Продолжить');
  await page.locator('#note').fill('Не потерять мысль');await page.getByRole('button',{name:'Сохранить мысль',exact:true}).click();await page.locator('#view-notes').click();assert.ok(await page.getByText('Не потерять мысль',{exact:true}).isVisible());await page.getByLabel('Закрыть',{exact:true}).click();
  await page.locator('#recap-open').click();await page.locator('#record').click();await page.waitForFunction(()=>document.querySelector('#record').textContent.includes('Остановить'));await page.waitForTimeout(700);await page.locator('#record').click();await page.waitForSelector('audio');assert.ok(await page.locator('.record-download').isVisible());await shot('voice-recap');await page.locator('#dialog-close').click();
  await page.locator('#recap-open').click();await page.locator('#recap-form textarea').fill('Сегодня записан один дубль.');await page.locator('#recap-form button.primary').click();await page.reload();await page.locator('#recap-open').click();assert.equal(await page.locator('#recap-form textarea').inputValue(),'Сегодня записан один дубль.');await page.locator('#dialog-close').click();
  await page.locator('.preview-settings summary').click();
  await page.selectOption('#scenario','dense');assert.equal(await page.locator('.task').count(),14);await page.locator('.preview-settings summary').click();await shot('dense-1440');
  await page.setViewportSize({width:1280,height:900});await shot('dense-1280');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const boxes=await page.locator('.core .task-title,.core .task-side').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};}));assert.ok(boxes[0].right<=boxes[1].left);
  await page.locator('.preview-settings summary').click();await page.selectOption('#scenario','empty');await page.locator('.preview-settings summary').click();await shot('empty-1280');assert.equal(await page.locator('.task').count(),0);await page.locator('#empty-add').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'task-name');
  await page.locator('.preview-settings summary').click();await page.selectOption('#scenario','regular');await page.locator('.preview-settings summary').click();await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.shadow-art').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
  await page.getByRole('button',{name:'8 сентября',exact:true}).click();assert.equal(await page.locator('.task').count(),0);await page.getByRole('button',{name:'7 сентября',exact:true}).click();assert.equal(await page.locator('.task').count(),5);
  await page.locator('#day-close').click();await page.locator('#confirm-close-day').click();assert.equal(await page.locator('.task').count(),5);assert.equal(await page.locator('#day-close').innerText(),'Открыть день снова ↗');await page.locator('#day-close').click();
  await page.setViewportSize({width:1440,height:1000});await shot('final-1440');
  // A failed local write must not alter the visible completion state.
  await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new Error('Storage full');};});
  await page.getByRole('button',{name:'Выполнить: Записать первый дубль для Satoru',exact:true}).click();
  assert.equal(await page.locator('[data-task="video"].done').count(),0);
  assert.ok(await page.locator('#notice.error').isVisible());
  await page.reload();
  // Permission denial has a useful text fallback, no fake recording success.
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});
  await page.locator('#recap-open').click();await page.locator('#record').click();
  await page.waitForFunction(()=>document.querySelector('#mic-status').textContent.includes('Микрофон недоступен'));
  assert.equal(await page.locator('audio').count(),0);await page.locator('#dialog-close').click();
  await page.reload();await page.locator('#recap-open').click();await page.locator('#record').click();
  await page.waitForFunction(()=>document.querySelector('#record').textContent.includes('Остановить'));await page.locator('#dialog-close').click();
  await page.waitForTimeout(200);assert.equal(await page.locator('dialog[open]').count(),0);
  const webMCP=await page.evaluate(()=>!!document.modelContext?.registerTool);
  assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
  const report={passed:true,checks:['completion and undo','direct time edit','direct duration edit','overlap warning','create and reload persistence','HTML escaping','focus pause','note persistence','microphone record-stop-download','recap text persistence','dense 1440/1280','empty day','reduced motion','date navigation','close day without deletion'],errors,failures};
  report.checks.push('all images decoded','composer in first viewport','failed storage does not show completion','microphone denied fallback','close while recording');
  report.webMCP=webMCP?'supported; read tool requires native caller verification':'unsupported in this Chrome run; not claimed verified';
  await writeFile(new URL('./qa/report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
